### ISSUE TITLE
Installer not working in Ubuntu 16.04 due to non available libc version

### ISSUE THREAD

**Issue by albertoferna** [DualSPHysics/DesignSPHysics#1]
Just tried to install using the installer in the oficial webpage. I get back an error:

```
Traceback (most recent call last):
  File "installer.py", line 17, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 687, in load_module
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIg0Ti4v/libexpat.so.1)
[19915] Failed to execute script installer
```

In fact, version 2.25 of libc is not available in 16.04 as far as I know. The higher version in the repositories (including backports) is 2.23

**Comment by LoreDocasar** [comment]
Maybe you have an older version of Linux... Can you update it? If this is not possible, in the README.md file you can check the "Installing a development build" section for another method to install DesignSPHysics if the installer doesn´t work in your system.

**Comment by albertoferna** [comment]
It depends what you call an old version of linux. I'm running ubuntu 16.04. Ok, it is not the latest LTS but some apps are still not present in 18.04 (which is the latest LTS). I'm running kernel 4.15 which is also reasonably recent.
The problem is that changin that library version would break the whole system as it is a basic one.
About the read.me, I started with it before using the installer. It was giving me different issues and that was the reason I tried the installer.
I'll take a look at it again. DualSPHysics is working in my system so I could always create the cases manually, but I wanted to try FreeCAD's plugin

**Comment by LoreDocasar** [comment]
A way to manually install a release version has been now described in the readme.md. Can you check the "Installing a release version" section and try again?

**Comment by albertoferna** [comment]
I have to check in my desktop when I get a moment. I have checked in my laptop but it is running 18.04 with is the latest ubuntu LTS.
In ubuntu 18.04 the installer works well. There is an issue that I think should be improved. I don't have an nvidia card in my laptop. Therefore, I selected to run using cpu. However, the executable used by default uses cuda. It is not a big deal as I fixed by change the path in DSPH setup to DualSPHysics4.2CPU_linux64. But, there was no error message or anything like it. The GUI just sit there with calculation at 0. Obviously it can be figured out with a little bit of tinkering, but I think it wold be better if the correct executable was set up if no cuda libraries are detected, or at least to trow an error.

**Comment by albertoferna** [comment]
Following the manual procedure works.
In conclusion the situation is the following:
- Release version and development version can be installed only manually in ubuntu 16.04
- Release version can be installed in ubuntu 18.04 using the installer

I don't know if this closes the issue as the installer does not work in ubuntu 16.04. But, certainly there is a work around and it works correctly in the next version (18.04)

**Comment by LoreDocasar** [comment]
I’m glad it works in your computer, i’ll see if I can fix the installer in a further version. Thanks for reporting the issue!
