### ISSUE TITLE
Coupling with chrono

### ISSUE THREAD

**Issue by FatimaAzhar** [DualSPHysics/DesignSPHysics#10]
Hello,
How do I make the "coupling chrono" tab in "special" tab of designSPHysics GUI active? 
I have already compiled the chrono code using cmake with procedure given on http://api.projectchrono.org/tutorial_install_chrono.html

**Comment by LoreDocasar** [comment]
You are probably using an earlier version of the macro and that is why it is not active.
Download the new version and you will see the CHRONO option active.

You can download it from the official page:

    https://design.sphysics.org/

Or from github:

    https://github.com/DualSPHysics/DesignSPHysics

**IMPORTANT**
This new version is already compatible with FreeCAD 0.18 so it does NOT work with FreeCAD 0.17
