### ISSUE TITLE
how to make many solid objects with the same materials

### ISSUE THREAD

**Issue by a652437264** [DualSPHysics/DesignSPHysics#101]
I want to create multiple small spheres with aluminum blocks, but when the same material is used for two or more spheres, an error appears saying that [Text: Name-Value already exists.]. Please help me

**Comment by zlotny** [comment]
Hi there. I've tried your issue and I could create 2 spheres with the same material without any issue.

I tried first to create an sphere with mk bound 0 and another one with mk bound 1, then going to materials on each one, setting aluminium and saving the case. There was no error and the XML had the correct information written:
![image](https://user-images.githubusercontent.com/6155245/149927210-82895960-68d7-4ba4-af24-1e38747db983.png)

I also tried to set the second sphere to mk bound 0, so both were the same type of boundary object. When I opened the material panel it was already set to aluminium (makes sense, as MK0 is aluminium).

I could not find the error, could you please specify the steps to get to that? Thanks.

**Comment by zlotny** [comment]
This was the same issue as #99 which explained that the error appeared while running Gencase.

It should be fixed via commit fe118fe1f9c38c621fd65ba2e7dcf622e169bf47

Please update or reinstall DesignSPHysics. Thanks for reporting the error!
