### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by zhu-hui-ling** [DualSPHysics/DesignSPHysics#103]
When you call the Designsphysics macro using Freecad, click Install error DesignSphysics.FCmacro, then click Execute, and there is no interface where you can use Designsphysics.
![图片](https://user-images.githubusercontent.com/84692809/132934161-729b2d47-15f9-4fb8-928d-f161c558d366.png)
![图片](https://user-images.githubusercontent.com/84692809/132934167-e7511bf7-5df7-46e0-8b87-27072946f2d4.png)

**Comment by zlotny** [comment]
Hello there. Can you open the Report View and then try to execute DesignSPHyiscs to see what happens?

Here's how:
![image](https://user-images.githubusercontent.com/6155245/149925583-20a38259-5735-4286-b8a7-8d99abbd3704.png)

**Comment by luzpaz** [comment]
This ticket can be closed
