### ISSUE TITLE
Error with FreeCad 0.19

### ISSUE THREAD

**Issue by mateo1105** [DualSPHysics/DesignSPHysics#104]
I installed the Version of DesignSPHysics in FreeCad 0.19 and it does not recognize the executable of DualSPHysics. I become the following error : 

> These executables do not correspond to their appropriate tool or don't have execution permissions:
./dualsphysics/bin/DualSPHysics5.0_linux64`

When i tried to run the executable alone it becomes following error : 

> ./DualSPHysics5.0_linux64: error while loading shared libraries: libChronoEngine_parallel.so: cannot open shared object file: No such file or directory

**Comment by zlotny** [comment]
Hi there. There was an error made by me that led to the repo not including the file libChronoEngine_pararllel.so in the past. You can download it here:

https://github.com/DualSPHysics/DesignSPHysics/raw/master/dualsphysics/bin/libChronoEngine_parallel.so

And then place it on the addon directory under dualsphysics/bin/

If you don't know how to do that you can just uninstall and reinstall the macro, as it is already fixed upstream.

Sorry about that. I'm closing the issue as it is not present on the current versions of the software.
