### ISSUE TITLE
Failed to Save Case and Run GenCase

### ISSUE THREAD

**Issue by LingxiaoGao** [DualSPHysics/DesignSPHysics#109]
I was trying to click "Open in ParaView" from "Save&GenCase" dialog, but it encountered an error.

My paraview path is correctly set up in "setup plugin"
C:\Program Files\ParaView 5.10.0-Windows-Python3.9-msvc2017-AMD64\bin\paraview.exe

DesignSPHysics version: 0.6.1.2201-31-01
Platform: Windows-10-10.0.19041
FreeCAD Version: 0.19.24267 +99 (Git)
Exception type: <class 'PermissionError'>
Exception value: [WinError 5] Access is denied
Traceback:

  File "C:\Users\Lingx\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\widgets\gencase_completed_dialog.py", line 107, in on_open_paraview_menu
    subprocess.Popen([Case.the().executable_paths.paraview, "--data={}\\{}".format(Case.the().path + "\\" + Case.the().name + "_out", action.text())], stdout=subprocess.PIPE)
  File "C:\Program Files\FreeCAD 0.19\bin\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\FreeCAD 0.19\bin\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

**Comment by imestevez** [comment]
It seems you are trying to save/execute the case in a folder without permissions.
