### ISSUE TITLE
Fail to run the simulation

### ISSUE THREAD

**Issue by celineman** [DualSPHysics/DesignSPHysics#110]
Hello, I got the problem that I cannot run the simulation on FreeCAD. 

I was doing the Wave Tank tutorial and when I clicked the button, it popped out an error box saying that 
there is an error occurring during execution. Please see the following and how can I solve it?

*** ERROR: Some boundary particle was excluded. ***
TimeStep: 0.000998  (Nstep: 4)
Total boundary: 4  (fixed=0  moving=4  floating=0)
Excluded for: position=4  rhop=0  velocity=0
Some boundary particle exceeded the +Z limit (top limit) of the simulation domain.
 

*** Exception (JSphCpuSingle::AbortBoundOut) at ..\source\JSph.cpp:2472
Text: Fixed, moving or floating particles were excluded. Check VTK file Error_BoundaryOut.vtk with excluded particles.

**Comment by celineman** [comment]
Again I got another error while running the simulation. There was a box popping out that said that "DesignSPHysics encountered an error and please report the developer the following details."

DesignSPHysics version: 0.6.1.2201-31-01
Platform: Windows-10-10.0.22000

FreeCAD Version: 0.19.24267 +99 (Git)
Exception type: <class 'RuntimeError'>
Exception value: The executable ./dualsphysics/bin/DualSPHysics5.0_win64.exe doesn't have executable permissions and DesignSPHysics cant provide it for you. Please give execution permissions to that file.
Traceback:

  File "C:\Users\celin\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\widgets\dock\dock_simulation_widget.py", line 150, in on_ex_simulate
    ensure_process_is_executable_or_fail(Case.the().executable_paths.dsphysics)
  File "C:\Users\celin\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\executable_tools.py", line 84, in ensure_process_is_executable_or_fail
    raise RuntimeError(__("The executable {} doesn't have executable permissions and {} cant provide it for you. Please give execution permissions to that file.").format(cli_path, APP_NAME))

**Comment by cvdr888** [comment]
I'm having the same issue with the wavetank case study with piston motion given by external file. Using an inlet condition work though.
