### ISSUE TITLE
add_object_to_sim Not Found

### ISSUE THREAD

**Issue by coolp4n** [DualSPHysics/DesignSPHysics#116]
'Case' object has no attribute 'add_object_to_sim'
Hi there.
My DSPH Version is "0.6.1.2102-24-04"
When I create a new case  based on an existing Freecad Document, it would call the function ("on_new_from_freecad_document") from mod/widgets/dock/dock_pre_processing_widget.py.  In this function, the instance(Case.the()) calls a instance method --"add_object_to_sim". 
But it's strange that I cant find any method named after 'add_object_to_sim', even in the whole project.
Looking forward to your reply asap.
Thanks a lot

**Comment by imestevez** [comment]
After you execute the macro `DesignSPHysics.FCMacro`, go to the top panel of FreeCad and click on `View `> `Panels` > `DSPH Object Properties`.
