### ISSUE TITLE
Error Executing GenCase

### ISSUE THREAD

**Issue by Tom467** [DualSPHysics/DesignSPHysics#122]
I have downloaded FreeCAD and then using the DesignSPHysics addon.  When I save the file and click ''Run GenCase'', it produces a message

''This action will remove the data generated before''

If I click OK it then says

''Error executing GenCase. Did you add objects to the case? Another reason could be memory issues. View details for more info''.

The information report does not provide any more detail apart from a file did not load, has anyone experienced this error message before or knows what is causing it to happen? (I do have a version of Paraview installed and have the pathway for it in Setup Plugin.

**Comment by eliasaaash** [comment]
same problem :(

**Comment by imestevez** [comment]
Hello, 
Can you share more information about the error, some screenshot or indicate which file is missing?

**Comment by eliasaaash** [comment]
![error](https://user-images.githubusercontent.com/119148775/204288618-d05ba7e4-d1ce-42c8-8c2d-63e9d4a8a22b.jpg)

**Comment by imestevez** [comment]
I think the error is related to the space that there is in the user name folder where the case is generated. Try saving the case to a different path without spaces or any special characters, accents, etc.
