### ISSUE TITLE
When installing 4 mooring lines

### ISSUE THREAD

**Issue by nomukou** [DualSPHysics/DesignSPHysics#123]
I have a question regarding the 3D representation of a mooring for an agitating floating body floating above the waves. In the program I created, I was able to rotate the mooring correctly when two moorings were placed. However, if I place 4 moorings on 4 corners of the floating body, I get an error. What is the problem with changing the number of moorings?

ver：DesignSPHysics 0,6,1,2102-24-04

**Comment by imestevez** [comment]
Hello, 
Can you share some information about the error you got?

**Comment by nomukou** [comment]
![MoorDyn Line Configuration 2022_12_13 14_04_21](https://user-images.githubusercontent.com/116057698/207231505-698a3f88-4805-4e52-8b56-2b6ae353676e.png)
![FreeCAD 0 20 2022_12_13 14_06_22](https://user-images.githubusercontent.com/116057698/207231507-cec9979b-2330-479c-868f-f88bfafdde38.png)
![MoorDyn Line Configuration 2022_12_13 14_03_41](https://user-images.githubusercontent.com/116057698/207231510-718fd867-d9da-42aa-8b76-e0d870080f83.png)
![MoorDyn Line Configuration 2022_12_13 14_03_54](https://user-images.githubusercontent.com/116057698/207231514-235a8f65-030c-419c-b808-9544a74e653f.png)
![MoorDyn Line Configuration 2022_12_13 14_04_09](https://user-images.githubusercontent.com/116057698/207231516-5395ceeb-891c-4892-98e8-a1fee5559a86.png)

**Comment by imestevez** [comment]
Try to specify the MKBound of the floating body to be moored in the option "Vessel connection"  instead of "None"

**Comment by luzpaz** [comment]
This probably can be closed ?
