### ISSUE TITLE
How to use MoorDyn+ in DesignSPHysics??

### ISSUE THREAD

**Issue by Mohsen-taherzadeh** [DualSPHysics/DesignSPHysics#125]
Hello dears
I am simulating the interaction of a moored floating object with waves using DesignSPHysics. The version used is 0.6.3 (24-09-2022). I have to use the "MoorDyn+" software to analyze the mooring lines, but in this version that I use, there is the "MoorDyn" software. How do I add the "MoorDyn+" software to DesignSPHysics and use it?
regards

**Comment by imestevez** [comment]
Hello, 
DesignSPHysics indicates the use of MoorDyn because MoorDyn+ is based on it. However, the only coupling available in the DualSPHysics package is the one with MoorDyn+. As soon as you run an example using moorings, you can see in details or in the Run.out file that MoorDyn+ is executed.

**Comment by Mohsen-taherzadeh** [comment]
Thank you for your guidance Dear Ivan
regards
