### ISSUE TITLE
Error in starting the simulation of a floating box with moorings

### ISSUE THREAD

**Issue by Mohsen-taherzadeh** [DualSPHysics/DesignSPHysics#127]
Hello Dears
I am simulating a floating box against regular waves using the coupled tools of Freecad, DesignSPHysics, and Moordyn based on the article "SPH simulation of floating structures with moorings" by Dominguez JM, et al. (2019). After the RunGencase, when I try to run it on the GPU, I get this error. What can you help me with?

regards

![Screenshot (243)](https://user-images.githubusercontent.com/58624189/205449325-4f5c2ea0-0451-484d-b226-71291ed84d44.png)

**Comment by imestevez** [comment]
That exception is launched because the mooring line solver is not able to properly solve a time step for the line 0. This happens when the user-defined properties of the mooring lines are not correct from a physical point of view
