### ISSUE TITLE
Natural Frequency for a floating structure

### ISSUE THREAD

**Issue by Mohsen-taherzadeh** [DualSPHysics/DesignSPHysics#130]
Hello dears
In order to obtain system dynamical properties such as damping ratio, natural frequency, etc., a free-decay test should be done. In this manner, I will obtain these properties for a floating box with mooring lines based on Domingues et al. 2019 simulation in DesignSPHysics. Is the natural frequency calculated automatically in DesignSPHysics for each degree of freedom? If not, how do I set an initial surge displacement when simulating a free-decay test?
 regards

**Comment by imestevez** [comment]
Hello, please post your doubts related to the SPH solver on the [DualSPHysics forum](https://forums.dual.sphysics.org/)
