### ISSUE TITLE
RUN chrono--error

### ISSUE THREAD

**Issue by WJJ509** [DualSPHysics/DesignSPHysics#132]
HI,guys

When I finished setting ‘chrono’ ,  the result shows ‘Text: Error reading xml - Element 'ompthreads' is invalid’. What should I do to run my model
![1](https://user-images.githubusercontent.com/126752761/222371720-614565b2-202e-45fc-8e10-da7d1911a72c.jpg)

![2](https://user-images.githubusercontent.com/126752761/222371818-f84ba900-9b20-4f75-98ef-581441de107d.jpg)

![3](https://user-images.githubusercontent.com/126752761/222371864-52db6b6d-5e69-4d03-a160-18d4344ca7c7.jpg)

regards

**Comment by imestevez** [comment]
The use of the multi-core module of Chrono is temporally disabled, so the <ompthreads> option is invalid. If you remove the line you highlighted in the .xml file, it should work.
This issue will be fixed in the next development.

**Comment by WJJ509** [comment]
Thank you very much for your suggestion. I tried to change it to ‘single core ’, but it still didn't work.
if I remove  the highlighted in the .xml file, I don't konw how to run it in designsphysics

Regards
