### ISSUE TITLE
Creating solitary wave with DesignSPHysics

### ISSUE THREAD

**Issue by VijayN10** [DualSPHysics/DesignSPHysics#134]
Hello!

I want to generate solitary wave using DesignSPHysics. I am able to create that with using dualSPHysics xml file using example case given with software. But I did not find any option to create solitary wave with DesignSPHysics.

![Screenshot 2023-03-03 191423](https://user-images.githubusercontent.com/104957980/222736716-6d417590-42b5-4b0b-a34e-072f3e0497d5.png)

Can anyone please help me with this?

Thank you.

**Comment by imestevez** [comment]
Hello, the definition of solitary waves is not implemented in the GUI. However, focused waves will be available soon in the next upgrade.
