### ISSUE TITLE
Reverse compatibility of xml file with DesignSPHysics (FreeCAD macro)

### ISSUE THREAD

**Issue by VijayN10** [DualSPHysics/DesignSPHysics#135]
Hello!

I have started using DualSPHysics/DesignSPHysics and enjoying the learning. I have a query regarding compatibility of dualsphysics with DesignSPHysics (FreeCAD macro).

I have generated case using DesignSPHysics and it created .xml file. When I change simulation parameters inside the freecad, it gets reflected in xml file. But when I try to do reveres, like changing the .xml file parameters, it does not updated in freecad.

Can anyone please help me, how can I achieve this?

Thanks!

**Comment by imestevez** [comment]
Hello, that functionality is not available yet
