### ISSUE TITLE
Import  DualSPHysics XML case file

### ISSUE THREAD

**Issue by alpinfra** [DualSPHysics/DesignSPHysics#136]
How can I import an existing DualSPHysics XML case file, e.g. from the DualSPHysics examples, into FreeCAD and solve it using DesignSPHysics? Functionality is mentioned in this presentation: https://dual.sphysics.org/3rdusersworkshop/data/_uploaded/dsph3presentations/Vieira_3rdWorkshop.pdf

**Comment by wulizhiren** [comment]
> How can I import an existing DualSPHysics XML case file, e.g. from the DualSPHysics examples, into FreeCAD and solve it using DesignSPHysics? Functionality is mentioned in this presentation: https://dual.sphysics.org/3rdusersworkshop/data/_uploaded/dsph3presentations/Vieira_3rdWorkshop.pdf

Hello, I also have the same question. Could you please tell me have you resolved this issue？

**Comment by GEORMC** [comment]
Hello,
Free cad and DSPHpysics that I have installed do not have XML import, I noticed it from your video, should I install another macro for it?
Regards,

**Comment by imestevez** [comment]
Hello, the XML import is deprecated and not available in the lastest versions of the code.

**Comment by GEORMC** [comment]
THanks for your reply.
So, how can I use the example files? they are XML format.
Thanks

**Comment by imestevez** [comment]
Yo can find a tutorial at the following link https://youtu.be/_sL1iQUJfs8?si=tdyOnSqwyfbHddeZ
