### ISSUE TITLE
[DesignSPHysics] Please create a SVG logo for this workbench

### ISSUE THREAD

**Issue by luzpaz** [DualSPHysics/DesignSPHysics#14]
This will be needed to the newly improved Addon Manager https://github.com/FreeCAD/FreeCAD-addons/issues/37

**Comment by luzpaz** [comment]
@LoreDocasar ping

**Comment by zlotny** [comment]
Hi there! Currently we don't have people in here that know how to do vector art, so for now we can't provide a logo for the addon manager. I'll try to work on a logo rework that could be easily vectorized soon.

I'll keep this open until we can look at this a bit further, sorry about that.

**Comment by luzpaz** [comment]
@zlotny we can post a request to FreeCAD subforum and they may do it for you?

**Comment by zlotny** [comment]
That's a possibility. I'll talk tomorrow with the team in here to check if they want to do that as it is kind of a style decision.

I'll make a post if we decide to try to work with people wanting to contribute. Thanks for the suggestion!

**Comment by luzpaz** [comment]
bump

**Comment by luzpaz** [comment]
Currentlythis is hwo DesignSPHysics looks like in the Addon Manager:  
![image](https://user-images.githubusercontent.com/4140247/64270068-f0e8fe00-cf08-11e9-9ca1-1fe9eacb2a40.png)

**Comment by zlotny** [comment]
Hi there, don't work on august as the most part of the team is on vacation, so hence the delay.

I made the logo myself. It's probably not perfect as I learned to use Inkscape like a few days ago, but this could suffy. Also I'm planning to replace the current icons on the application with vector files so it scales better.

I attach to you here the minified svg insize a zip.
[designsphysics-minified.zip](https://github.com/DualSPHysics/DesignSPHysics/files/3582934/designsphysics-minified.zip)

**Comment by luzpaz** [comment]
Hey @zlotny just a heads up that we've merged the SVG in to the Addon Manager with a caveat, we altered it (documented in https://github.com/FreeCAD/FreeCAD/pull/2623) because the icon was far too large and detailed for the Addon Manager UI. If you have an issue with this please make a PR to FreeCAD master. Thanks!

**Comment by zlotny** [comment]
Couldn't check this earlier as I was pretty busy these days. The logo is fine. The one I did includes a raster that makes the final file pretty large, it seems.

However for a small icon inside the AddonManager that would do fine.

Thanks for your work and to the user _vocx_ for adapting the SVG.
