### ISSUE TITLE
Issues installing DesignSPHysics 

### ISSUE THREAD

**Issue by Spoukiwaikiki** [DualSPHysics/DesignSPHysics#142]
Hi,

I am trying to install DesignSPHysics, to be able to use DualSPHysics. But I keen on running into issues.
I am using FreeCAD 0.20.2, and I have tried both loading it through the macro tool, but I get the following error
![image](https://github.com/DualSPHysics/DesignSPHysics/assets/133830847/48a90f32-e7ff-437f-aeb5-6339cb25f5bb)

Or using the add-on tool which gives me the following error
![image](https://github.com/DualSPHysics/DesignSPHysics/assets/133830847/b90aba58-b289-4c72-a65b-66fc277bc67e)

Any help would be much appreciated

Thank you

**Comment by Leinen** [comment]
It looks like the link is broken: 

Broken-Link: https://github.com/DualSPHysics/DesignSPHysics/blob/main/README.md
Correct-Link: https://github.com/DualSPHysics/DesignSPHysics/blob/master/README.md
