### ISSUE TITLE
NOT ABLE TO ADD OBJECT IN DSPH SIMULATION

### ISSUE THREAD

**Issue by joshdm16** [DualSPHysics/DesignSPHysics#143]
HI, tried many times to click the dsph window but no button to add object. I read some thread comments before about the problem such as changing the language to english but still not working. I am about to uninstall the designsphysics but there is popping error. It needs to be reported to the developer. Please help me with this? I am still new in freecad and I need this for my research. Thank you

**Comment by luzpaz** [comment]
Missing About info (which shows the version of FreeCAD you're using and version of DSPH
