### ISSUE TITLE
Future implementation of multiphase?

### ISSUE THREAD

**Issue by aepoc** [DualSPHysics/DesignSPHysics#145]
Is the team planning on including an "air fill box" option in the future so that we can simulate multiphase projects?

Thanks everyone for your contributions!

**Comment by imestevez** [comment]
Hello, unfortunately we do not plan to include that functionality in DesignSPHysics.
However, you can use it by downloading the full package of DualSPHysics (v5.2.0) from: https://dual.sphysics.org/downloads/
In this package you will find several examples in the folder DualSPHysics_v5.2/examples/mphase_liquidgas
