### ISSUE TITLE
Cannot Run Gencase for FreeCAD 0.21.0

### ISSUE THREAD

**Issue by Muyii3** [DualSPHysics/DesignSPHysics#148]
23:38:23  Traceback (most recent call last):
23:38:23    File "C:\Users\Liu\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\widgets\dock\dock_pre_processing_widget.py", line 255, in on_execute_gencase
    total_particles_text = output[output.index("Total particles: "):output.index(" (bound=")]
23:38:23  ValueError: substring not found
23:38:23

**Comment by imestevez** [comment]
Could you check the path where you are saving/generating the case? This issue could be because the path contains some special character or spaces.
In any case, please try downloading the new version [v0.7.0](https://github.com/DualSPHysics/DesignSPHysics/releases/tag/0.7.0)

**Comment by luzpaz** [comment]
@Muyii3 ping
