### ISSUE TITLE
Problems installing DesignSPHysics in FreeCAD

### ISSUE THREAD

**Issue by dirasuma** [DualSPHysics/DesignSPHysics#149]
Hello

I am trying to install DesignSPHysics and have done both the installation manually according to the directions and from the addon manager in FreeCAD 0.21.1. I still couldn't do it and encountered the following error code:
![image](https://github.com/DualSPHysics/DesignSPHysics/assets/145153825/4f5779b0-0323-4c06-892e-016b5245f39d)
Does anyone have a similar problem or solution?

**Comment by aepoc** [comment]
I’m currently running into the same issue.  I saw the new release so I updated free cad and then tried updating dualsphysics and am getting the same or similar errors.

**Comment by imestevez** [comment]
This issue should be fixed and the release has been updated. Please try to download it again.

**Comment by dirasuma** [comment]
> This issue should be fixed and the release has been updated. Please try to download it again.

Now it can be used. Thank you so much.

**Comment by imestevez** [comment]
Sorry, I missed your comment [aepoc](https://github.com/aepoc). The issue was fixed in the latest commit. Please try again to download it.

**Comment by aepoc** [comment]
Do you think this could be a work IT access thing?  I was able to automatically install the previous version in FreeCad v20.  I'm worried that if I update on my personal computer then I will no longer have access to a GUI for DualSPHysics...

When I download, unzip, rename and place files and folders in their correct locations, I still get an error upon opening the macro:

[DEBUG] [DesignSPHysics] main.py:151 -> Subscribing selection change monitor handler to freecad object tree item changed.

Then many main.py:94 Invalid document environment found. Disabling case-related tools.

I'm hoping somebody could steer me in the correct direction.

Thanks!

**Comment by imestevez** [comment]
Do not worry about that messages, they are debug and log information showed on the `Report view` but not errors of the code.
After you load the macro, check on the rigth panel if FreeCAD is loading the `DesignSPHysics 0.7.0 (15-09-2023)` version.

**Comment by aepoc** [comment]
The correct macro is being loaded (DSPH0.7.0 (15-09-2023)).  I set up a case that I've run in a previous version and am unable to get gencase to output anything:

Traceback (most recent call last):
09:42:32    File "C:\Users\***\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\widgets\dock\dock_pre_processing_widget.py", line 269, in on_execute_gencase
    total_particles_text = output[output.index("Total particles: "):output.index(" (bound=")]
09:42:32  ValueError: substring not found

**Comment by imestevez** [comment]
After loading the case from a previous version, save it again (better to a different path) and make sure there are no spaces or special characters in the path

**Comment by aepoc** [comment]
i started this one from scratch.  I just based it off one that worked for me previously.  I should note that when examining the .VTK files that gencase did produce, its clear it didn't even get to the fillbox command as there is no fluid to be seen (same for plungers un wavemaker).

Thanks again for your support!!

**Comment by imestevez** [comment]
Could you share the path where you are saving and executing the case? 
This error appears when spaces, accents, or special characters are used in the path. 
There is a similar thread on this topic #148

**Comment by aepoc** [comment]
ok I've been able to get gencase to complete...  that one was my mistake but I still cannot get a simulation to run.

And Yes, I've run into the space thing before.  The path is:
D:\SPH\DesignSPHysics\X05\Roller\TTRoller\TTRoller_out

Should I be loading the macro through the mod folder or through the copy in the macro folder?  I've tried both

**Comment by aepoc** [comment]
well, just for the F*** of it, I updated my GPU drivers...  no luck.  I did however have luck uninstalling and then reinstalling via the automatic route and everything seemed to work.  Now I just get the "Update GPU driver" error when I simulate

**Comment by aepoc** [comment]
So I have finally been able to complete a simple simulation.  looks like the normals on the .stl I was importing were incorrect.  This didn't effect the study in the previous version but perhaps there's something wrong with my stl(s).  Anyway thanks for the update and the help to get it going!

**Comment by aepoc** [comment]
I should note that I've been able to run several 2d simulations with boxes made in designsphysics.  I have not yet tried to import geometry as I seem to have trouble with generating normals for mDBC...  Anyway; I just wanted the community to know that my particular issue seems to be coming from a bad stl.  Thanks for the support!

**Comment by imestevez** [comment]
Please share your questions related to the use of the SPH solver or their functionalities in the[ DualSPHysics forum](https://forums.dual.sphysics.org/) to be discussed with the developers and the community.
