### ISSUE TITLE
Can DualSPHysics be applied to fluid flow problems in porous media?

### ISSUE THREAD

**Issue by wwgfbz** [DualSPHysics/DesignSPHysics#15]
Since the existing SPH code is suitable for wave flow, macro fluid flow such as ocean fluid flow. The SPH meshless method has great advantages when it is used to treat microporous media. It is found that the existing SPH code is not suitable for describing microfluidic flow. We now intend to modify the existing macroscopic fluid code to describe the fluid flow in the microporous medium. Is it feasible to do this?

**Comment by zlotny** [comment]
This repository is strictly related to the user interface for DualSPHysics within FreeCAD, not for the SPH implementation. Please use the [DualSPHysics issues](https://github.com/DualSPHysics/DualSPHysics/issues) or [the forum](https://forums.dual.sphysics.org/)
