### ISSUE TITLE
give execution permissions

### ISSUE THREAD

**Issue by TShorlar** [DualSPHysics/DesignSPHysics#150]
DesignSPHysics version: 0.7.0 (15-09-2023)
Platform: Windows-10-10.0.22621
FreeCAD Version: 0.21.0
Exception type: <class 'RuntimeError'>
Exception value: The executable ./dualsphysics/bin/DualSPHysics5.0_win64.exe does not have executable permissions and DesignSPHysics cannot provide it for you. Please give execution permissions to that file.

**Comment by imestevez** [comment]
Version 0.7.0 (15-09-2023) was realeased to be used with DualSPHysics v5.2, so the executable `DualSPHysics5.0_win64.exe` is no longer available in the shared package. Please follow the next steps:

1. Look for the executbale `DualSPHysics5.2_win64.exe` in the folder `DesignSPHysics-0.7.0/dualsphysics/bin`
2. Open the macro `DesignSPHysics.FCMacro`
3. Click on `Setup Plugin`
4. Make sure that the field `DualSPHysics Path` contains `./dualsphysics/bin/DualSPHysics5.2_win64.exe`
