### ISSUE TITLE
main.py error.

### ISSUE THREAD

**Issue by MSSchliewe** [DualSPHysics/DesignSPHysics#153]
I'm getting a loop error related to the main.py file, right after running DesignSPHysics 0.7.0 in FreeCAD 0.21.1
![error-mainpy](https://github.com/DualSPHysics/DesignSPHysics/assets/144745650/d9e67227-adc2-4500-87f3-326d5e3f1039)

**Comment by imestevez** [comment]
That message is debugging information showed in the `Report View`, not an error. After you create a `New Case` or `Load Case` it should not appear.
