### ISSUE TITLE
Failed to Run GenCase

### ISSUE THREAD

**Issue by xiesi-user** [DualSPHysics/DesignSPHysics#154]
I was trying to click "Run GenCase" ,but it encountered an error.
DesignSPHysics version: 0.7
FreeCAD Version: 0.21
Traceback:
 File "C:\Users\21717\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\widgets\dock\dock_pre_processing_widget.py", line 269, in on_execute_gencase
    total_particles_text = output[output.index("Total particles: "):output.index(" (bound=")]
ValueError: substring not found

**Comment by imestevez** [comment]
Try to save the case in a path without spaces, special characters and accents.

**Comment by Chullll** [comment]
> Try to save the case in a path without spaces, special characters and accents.

I've done this, but the problem hasn't been solved yet. Is there any other solution?

**Comment by imestevez** [comment]
This error appears when the program is not able to find the executables and/or the output folder. Please following the next tips:

- Choose a path with read, write and execution permissions.
- Note that the binaries of DualSPHysics work only for Lunux and Windows.
- Make sure that there is no any special character, delimiting characters, any letter with accent, etc. Try in a very simple path close to the root folder where you have permissions.

**Comment by Chullll** [comment]
> This error appears when the program is not able to find the executables and/or the output folder. Please following the next tips:
> 
> * Choose a path with read, write and execution permissions.
> * Note that the binaries of DualSPHysics work only for Lunux and Windows.
> * Make sure that there is no any special character, delimiting characters, any letter with accent, etc. Try in a very simple path close to the root folder where you have permissions.

OK, thanks very much!
