### ISSUE TITLE
particles were excluded/ particles out

### ISSUE THREAD

**Issue by Chullll** [DualSPHysics/DesignSPHysics#157]
Hello!

When I run simulation, there appears a warning: More than 1% of current fluid particles were excluded in one PART and continuous error messages "particles out". How can I solve this problem?

**Comment by dirasuma** [comment]
It's mean that your bottom is not fully closed the fillbox or the water limit so the water is poured out from the case limit

**Comment by imestevez** [comment]
Fluid particles are leaving the domain. You should ensure that the fluid is properly locked, for example between boundary particles to prevent them from escaping. To solve this problem, you can run the fluid PartVTK and view the simulation with Paraview to find the error in the configuration.
