### ISSUE TITLE
Change 3D to 2D

### ISSUE THREAD

**Issue by smenzer15** [DualSPHysics/DesignSPHysics#159]
Setting up the floating sphere tutorial as per youtube video, having problems:

The buttons to change the object order do not allow to change the top item. Can workaround this one. Sorry about this in bold, can't change it!
------------------
Any attempts to change the simulation from 3D to 2D fail, get the following error report:

DesignSPHysics version: 0.7.0 (15-09-2023)
Platform: Windows-10-10.0.22621
FreeCAD Version: 0.21.1
Exception type: <class 'AttributeError'>
Exception value: 'NoneType' object has no attribute 'Width'
Traceback:

  File "C:\Users\stephen.menzer\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\widgets\dock\dock_pre_processing_widget.py", line 376, in on_2d_toggle
    Case.the().info.last_3d_width = fc_object.Width.Value

--------------------------
[code]
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * CfdOF 1.24.5
  * DesignSPHysics 0.7.0(15-09-2023)
  * dodo 1.0.0
  * fasteners 0.4.67
  * frame 0.1.1
  * Manipulator 1.5.0
  * QuickMeasure 2022.10.28
[/code]

**Comment by imestevez** [comment]
Try to change to 2D before adding any object to FreeCAD.

**Comment by smenzer15** [comment]
Good Morning

Thanks a lot for the quick reply.

I raised this on GitHub on Tuesday, but noticed on Wednesday that the workbench is ok after all, and I put this into an email to your gmail account, copy attached. Basically, I had the problem when working through a remote connection from home, but no problems when sitting in front of the workstation.  Never had that with Freecad before.

For your information, I am new to Dualsphysics but ok with OpenFoam and Elmer. 3D static FEA is routine.

As part of an ongoing R&D project, I try to simulate a tank overflow. The overflow is essentially a 90deg elbow fitted to a storage tank with downcomer pipe. I can design this a crested circular weir, but am looking for an independent method to verify. OpenFoam and Elmer both struggle with the free surface in a partially filled circular pipe. Having said that, grit methods are probably ok in a square overflow but haven't investigated in detail, as this is not what we are selling.

I probably have many more questions while I am learning your package!

Kind regards

                Stephan

------------------
Stephan Menzer
Technical Manager
Chem Resist Group Ltd
Lockway
Ravensthorpe Industrial Estate
Dewsbury, W. Yorks, WF13 3SX

Phone:  01924 499466
Fax:        01924 490334
Mobile: 07525 907314

***@***.***<https://www.chemresist.com/>

Follow us
***@***.***<https://www.facebook.com/Chem-Resist-Group-Ltd-1001866846656382/> ***@***.*** <https://www.linkedin.com/company/chem-resist-group-ltd/?viewAsMember=true>  ***@***.*** <https://twitter.com/Chem_Resist>  ***@***.*** <https://www.youtube.com/channel/UC_jUqI9x-sjJyHx3CYZ6QEw>
