### ISSUE TITLE
Modelling floating cube in DesignSPHysics

### ISSUE THREAD

**Issue by FatimaAzhar** [DualSPHysics/DesignSPHysics#16]
How can I add  parameters for Chrono such as coeff. of friction, young's modulus etc in the GUI? Should i manually edit xml file or write it down in "additional parameters"

It will be helpful if more tutorials are available for DesignSPHysics GUI for Chrono and inlet/outlet boundary!

**Comment by zlotny** [comment]
Chrono and Inlet/Outlet are currently a work in progress, specially on the GUI.

For now I'll suggest to create the case in DesignSPHysics until you feel "well enough" with the result, and then continue using DesignSPHysics with the command line interface.

Take in mind this GUI is designed to "keep up" with the DualSPHysics code with no special focus on replacing the general XML/CLI approach, but to make it simpler to start using the DualSPHysics de package, so things could take a while to implement.

Sorry about the inconvenience, we're going to make some changes in chorno and inlet/outlet soon, as well as a general documentation for DesignSPHysics.
