### ISSUE TITLE
Value of Kfric

### ISSUE THREAD

**Issue by 8ryoooooooo** [DualSPHysics/DesignSPHysics#162]
Hello.

I want to change the value of Kfric to whatever value I like. For that purpose, should I change the value of “Kfric” in default-materials.json?
If not, please tell me how to change the value of Kfric.

**Comment by imestevez** [comment]
To change the value of any parameter of material properties or add a new material, you have to modify the file `default-materials.json`.

**Comment by 8ryoooooooo** [comment]
> To change the value of any parameter of material properties or add a new material, you have to modify the file `default-materials.json`.

Thank you for your reply.
I learned that I can change the friction coefficient by editing "default-materials.json".
On the other hand, is it possible to express not only the dynamic friction coefficient but also the static friction coefficient by changing the "Ratio between static/dynamic friction" value in the "moordyn parameter configuration"?

Example
Kfric(dynamic friction coefficient)=0.5
static/dynamic=2.0
→static friction coefficient=1.0
