### ISSUE TITLE
Non-newtonian fluid in Designsphysics

### ISSUE THREAD

**Issue by Mysticor** [DualSPHysics/DesignSPHysics#165]
Hello, and sorry to ask here. I am trying to create a non-Newtonian fluid simulation in DesignPhysics, but I can't find where to modify the fluid parameters or how to define the fluid as non-Newtonian. Could you please tell me how to create a non-Newtonian fluid in DesignPhysics? If DesignPhysics does not yet have this feature, could you suggest an alternative method? Thank you.

**Comment by imestevez** [comment]
Hello, the non-Newtonian implementation is not yet available through the GUI DesignSPHysics. You can use that feature directly with the DualSPHysics package (v5.2.1) available at https://dual.sphysics.org/downloads/. In this package, you will find several examples to run the code in `examples/mphase_nnewtonian`
