### ISSUE TITLE
Can tell me about mDBC? Help!

### ISSUE THREAD

**Issue by 8ryoooooooo** [DualSPHysics/DesignSPHysics#168]
Hello.
I would like to perform an analysis using mDBC to eliminate the gap between the fluid and the boundary.
However, when mDBC was selected and ran, the following error occurred.

```
*** WARNING: There are 15002 of 15002 fixed or moving boundary particles without normal data.

*** WARNING: There are 1331 of 1331 floating particles without normal data.

*** Exception (JSphCpuSingle::ConfigBoundNormals) at DualSPHysics/source/JSph.cpp:1337

Text: No valid normal vectors for using mDBC.

Finished execution (code=1).
```

I tried to solve the error by referring to DualSPHysics `Case_Ducking_Def.xml`, but I couldn't solve this error.
Please tell me how can I solve  this error.

**Comment by 8ryoooooooo** [comment]
> you need to tell the simulation to generate normals by setting initials = true in the DSPH Object Properties of the boundary object(s).  If you read my previous post, it can be tricky and I am experiencing an issue very similar to yours.  
> 
> 
>
>
thank you for your reply.
When I set normal vectors to geometry and boundaries, I got a "particle were excluded" error.
The boundary and geometry normal vectors are set as shown in the image.
Also, the system looks like the image, and I would like to perform an analysis in which a cube placed on the ground floats on water.
Am I setting the normal vector incorrectly?
I've just started using designsphysics, so there are a lot of things I don't understand, but I appreciate your help.
![image](https://github.com/DualSPHysics/DesignSPHysics/assets/150150676/cd950b7e-5a79-45b6-ad4f-81194aa2637b)

![image](https://github.com/DualSPHysics/DesignSPHysics/assets/150150676/83ffec65-1148-4c9b-a6fb-724949586661)

> Are you using an .stl or geometry that was created with primitives in freecad?
>
>
>
>
Boundaries and simple geometry are created in free CAD. The STL file created with Solid Works is inported.

**Comment by aepoc** [comment]
The only way I have been able to get mDBC to work with an STL was in 2D.  In that scenario, I chose Initials = True and in the dropdown I selected "normals - parts".  This function however is not available in 3D.  I have heard of others using a fillbox to "fill their solid geometry".  Cant remember if this was for mDBC or Density Diffusion or something else...  Sorry I'm not much help.  If you figure it out, please let me know because I have never had luck with STLs in 3D using mDBC.

**Comment by jmdalonso** [comment]
You can find an example of 3-D floating external STL using mDBC in the folder examples\mdbc\09_FloatingDuck of the DualSPHysics full package (https://dual.sphysics.org/downloads/).
This feature is not yet available in DesigSPHysics. You have to use the XML configuration file directly.
You can find more information at https://dual.sphysics.org/6thworkshop/user/pages/03.workshop/05.Programme/6DSW_mDBC_Crespo.pdf)

Best regards

**Comment by 8ryoooooooo** [comment]
thank you for your reply.

Does this mean that I can only do this by referring to the `Floating Duck xml` , rewriting it for myself, and executing it with a bat file?

**Comment by 8ryoooooooo** [comment]
thank you for your reply. 
If I am going to analyze it with designsphysics, should I use a slightly larger scale or a larger geometry or boundary?

**Comment by Zahramht** [comment]
> Hello. I would like to perform an analysis using mDBC to eliminate the gap between the fluid and the boundary. However, when mDBC was selected and ran, the following error occurred.
> 
> ```
> *** WARNING: There are 15002 of 15002 fixed or moving boundary particles without normal data.
> 
> *** WARNING: There are 1331 of 1331 floating particles without normal data.
> 
> *** Exception (JSphCpuSingle::ConfigBoundNormals) at DualSPHysics/source/JSph.cpp:1337
> 
> Text: No valid normal vectors for using mDBC.
> 
> Finished execution (code=1).
> ```
>  
> I tried to solve the error by referring to DualSPHysics `Case_Ducking_Def.xml`, but I couldn't solve this error. Please tell me how can I solve this error.

Hello, 
I hope you are doing well. I am also supposed to work with mDBC for my master's thesis, may I kindly ask if you have any tutorial using FreeCAD or if I can contact you via Email for your guidance?
Thank you very much for your time in advance,
Regards
Zahra

**Comment by 8ryoooooooo** [comment]
I have just started using the flow simulation tool which using FreeCAD (designsphysics), so there are many things I don't understand.
It may not be in a satisfactory way, but if you don't mind, I would be happy to help you by email or SNS .
You can also watch designsphysics tutorials from the playlist below.

[](https://youtube.com/playlist?list=PLwaIMU-iIzj0LXtoZMGFWMnKOSWynI6XK&si=u12bakm-PTss01pM)

[](https://youtube.com/playlist?list=PLwaIMU-iIzj3e6ofvN6gyKLLVV7zss84K&si=9lxdGlUMcpknmg-i)

**Comment by 8ryoooooooo** [comment]
I have just started using the flow simulation tool which using FreeCAD (designsphysics), so there are many things I don't understand.
It may not be in a satisfactory way, but if you don't mind, I would be happy to help you by email or SNS .
You can also watch designsphysics tutorials from the playlist below.

[DesignSPHysics tutorial ①]( https://youtube.com/playlist?list=PLwaIMU-iIzj0LXtoZMGFWMnKOSWynI6XK&si=u12bakm-PTss01pM )

[DesignSPHysics tutorial ②](https://youtube.com/playlist?list=PLwaIMU-iIzj3e6ofvN6gyKLLVV7zss84K&si=9lxdGlUMcpknmg-i)

**Comment by Zahramht** [comment]
> I have just started using the flow simulation tool which using FreeCAD (designsphysics), so there are many things I don't understand. It may not be in a satisfactory way, but if you don't mind, I would be happy to help you by email or SNS . You can also watch designsphysics tutorials from the playlist below.
> 
> [DesignSPHysics tutorial ①](https://youtube.com/playlist?list=PLwaIMU-iIzj0LXtoZMGFWMnKOSWynI6XK&si=u12bakm-PTss01pM)
> 
> [DesignSPHysics tutorial ②](https://youtube.com/playlist?list=PLwaIMU-iIzj3e6ofvN6gyKLLVV7zss84K&si=9lxdGlUMcpknmg-i)

Hello and thank you for your Message. Here is my Email : zahra.mohsenitakallu@mail.polimi.it
I would appreciate your help towards this matter.

**Comment by ZZ5151** [comment]
I tried the above suggestion in 2D with mDBC, but I didn't solve the problem. Is 2D also not available, or is my setting wrong?
