### ISSUE TITLE
mDBC with FreeCAD

### ISSUE THREAD

**Issue by Zahramht** [DualSPHysics/DesignSPHysics#171]
Dear All,
I was wondering if it is possible to use freecad to create a case with mDBC? I saw the previous question regarding the stl files and as mentioned it is not yet available.

**Comment by imestevez** [comment]
It is possible to define mDBC with DesignSPHysics usin the option initials. However, it is not possible for STLs using the GUI yet. To do that, you should use DualSPHysics directly https://dual.sphysics.org/

**Comment by luzpaz** [comment]
> However, it is not possible for STLs using the GUI yet  

Is this on the Roadmap ?

**Comment by luzpaz** [comment]
Interpreting that as a 'No'.
