### ISSUE TITLE
DesignSPHysics.py

### ISSUE THREAD

**Issue by GiuliaClai** [DualSPHysics/DesignSPHysics#176]
DesignSPHysics.py is nowhere in DesignSPHysics-0.7.0, I only find DesignSPHysics.FCMacro, how can I proceed?

**Comment by imestevez** [comment]
The DesignSPHysics.FCMacro is the tool you have to use to execute DesignSPHysics integrated into FreeCad. Check this https://github.com/DualSPHysics/DesignSPHysics?tab=readme-ov-file#installation-instructions

**Comment by ZZ5151** [comment]
So, designSPHysics.py is not needed anymore?

**Comment by ZZ5151** [comment]
I pressed the Addons... button for searching  DesignSPHysics but I can not search it.

**Comment by imestevez** [comment]
DesignSPHysics.py is not needed anymore.

You have to follow the steps:
1. Download the DesignSPHysics package and extract the compressed file.
2. Open FreeCad and navigate on the File menu to `Macro` -> `Macros`
3. A new window with the title `Execute macro`  will appear
4. In `User macros location`, navigate and select the folder with the DesignSPHysics package
5. Click **`DesignSPHysics.FCMacro`** and click **`Execute`**
