### ISSUE TITLE
Error: cannot open *.stl file

### ISSUE THREAD

**Issue by FatimaAzhar** [DualSPHysics/DesignSPHysics#18]
*.out file shows this error and does not generate *vtk files:

MAIN

*** Exception (JStlFile::IsBinaryFile)
Text: Cannot open the file.
File: Compound.stl

I am using the latest DesignSPHysics macro 0.5.1.1906-04
How can this be fixed

**Comment by LoreDocasar** [comment]
Hi Fatima,

The latest version is 0.5.1.1906-18, download it and try again please.
Here I leave the link:

    https://github.com/DualSPHysics/DesignSPHysics

Thanks for your comment!

**Comment by FatimaAzhar** [comment]
It works on new version! Thank you!
