### ISSUE TITLE
direction definition

### ISSUE THREAD

**Issue by GiuliaClai** [DualSPHysics/DesignSPHysics#181]
I set up a new single model, a cilinder fluid which should fall, at leatg in my idea. I got this error. Can anyone itell me where I can change the direction?

DualSPHysics5 v5.2.272 (12-06-2023)
====================================
Threads by host for parallel execution: 4
[Initialising JSphCpuSingle  28-02-2024 12:13:57]
ProgramFile=".../dualsphysics/bin/DualSPHysics5.2_win64.exe"
ExecutionDir=".../FreeCAD/Mod/DesignSPHysics"
XmlFile=".../caso-test/caso-test_out/caso-test.xml"
OutputDir=".../caso-test-CilindroV/caso-test/caso-test_out"
OutputDataDir=".../caso-test-CilindroV/caso-test/caso-test_out"
XML-App: GenCase v5.0.283 (05-06-2023)
XML-Vars (uservars + ctes): MResId=[0]  CaseName=["caso-test"]  Data2D=[0]  Data2DPosy=[0]  H=[0.0311769]  KernelSize=[0.0623538]  B=[0]  Gamma=[7]  Rhop0=[1000]  Dp=[0.015]  Gravity_x=[0]  Gravity_y=[0]  Gravity_z=[-9.81]  MassFluid=[0.003375]  MassBound=[0.003375]
XML-Vars (parameters): TimeMax=[0.5]  TimeOut=[0.05]

*** Exception (JRelaxZoneUniform::ReadXml) at DualSPHysics/source/JRelaxZoneUniform.cpp:153
Text: Error reading xml - Attribute 'direction' is invalid. missing. Only one axis can be set to non-zero
File: C:/Users/user/Desktop/NEW-COLL/caso-test-CilindroV/caso-test/caso-test_out/caso-test.xml(row:65)

Finished execution (code=1).

**Comment by imestevez** [comment]
The message says `Only one axis can be set to non-zero`. 
Therefore, you should check the `direction` of the `Relaxation Zone`->`Uniform velocity` and be sure you have only 1 axis set to 0.
