### ISSUE TITLE
Dualphysics issue

### ISSUE THREAD

**Issue by assiabe** [DualSPHysics/DesignSPHysics#182]
I got this error from dualphysics if anyone can help me with that

DesignSPHysics version: 0.7.0 (15-09-2023)
Platform: Windows-10-10.0.19045
FreeCAD Version: 0.21.2
Exception type: <class 'UnicodeDecodeError'>
Exception value: 'utf-8' codec can't decode byte 0xe9 in position 1711: invalid continuation byte
Traceback:

  File "C:\Users/DELL/Mécanique des fluides/Try 2/DesignSPHysics-0.7.0\mod\widgets\dock\dock_simulation_widget.py", line 123, in on_dsph_sim_finished
    output = "".join(run_file.readlines())
  File "C:\Program Files\FreeCAD 0.21\bin\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)

**Comment by imestevez** [comment]
Try to save the DesignSPHysics package and the simulation case to paths without spaces or accents.

**Comment by assiabe** [comment]
It worked! thank you so much.
