### ISSUE TITLE
How does one import an XML file into FreeCAD DesignSPH. 

### ISSUE THREAD

**Issue by SohailAusgur** [DualSPHysics/DesignSPHysics#183]
Hi, 

I have noticed, the option to import XML file is not in the same place as previous versions. I would like to import the examples in the GUI to have better visual on the example. 

Can someone please let me know how this is done. Is there something else to add to the Macro or download for DualSPH. 

Thank you.

**Comment by imestevez** [comment]
That option is not available in newer versions.

**Comment by SohailAusgur** [comment]
Thank you for the reply. 
Will it ever be back or is it scrapped for further versions?

**Comment by imestevez** [comment]
It is not currently under development, so it is not contemplated that it will be integrated in the short term. 
However, it may be decided to include it again in the future, but I cannot confirm that yet.

**Comment by SohailAusgur** [comment]
Thank you for the information. 

One last thing, would you have any research articles  or tutorial which i can follow  to learn more on how to set up the parameters for DualSPH. It all seems to be quite confusing and open ended from the theory guide and various PDFs I have looked into.

**Comment by BenjaminBasumatary** [comment]
Can I know the last version that provided the option for xml import?
