### ISSUE TITLE
Some boundary particle exceeded the +Y limit (back limit) of the simulation domain

### ISSUE THREAD

**Issue by TShorlar** [DualSPHysics/DesignSPHysics#185]
Hi everyone,

Please, I need your help regarding what could probably be wrong here and what should be done: 

"Some boundary particle exceeded the +Y limit (back limit) of the simulation domain.
 

*** Exception (JSphGpuSingle::AbortBoundOut) at DualSPHysics/source/JSph.cpp:2549
Text: Fixed, moving or floating particles were excluded. Check VTK file Error_BoundaryOut.vtk with excluded particles."

Thanks.

**Comment by imestevez** [comment]
Please, follow this similar thread #178
