### ISSUE TITLE
Pressure Sensor. Is that added in Pre-Processing or Post Processing? 

### ISSUE THREAD

**Issue by SohailAusgur** [DualSPHysics/DesignSPHysics#188]
![image](https://github.com/DualSPHysics/DesignSPHysics/assets/161238937/4c629bf2-361e-4154-b104-813f9daa6582)
See, this image with the Pressure Sensor. I want to know, is this added in the xml files in pre-processing or is it done in Paraview for Post Processing? Many Thanks.

**Comment by jmdalonso** [comment]
An example can be found in the full DualSPHysics package (download from https://dual.sphysics.org/downloads/).
In examples/main/05_SloshingTank/CaseSloshingAcc pressure is measured at a point in a fixed tank.
In examples/main/05_SloshingTank/CaseSloshingMotion pressure is measured at a point in a moving tank.
Best regards.
