### ISSUE TITLE
Run disabled

### ISSUE THREAD

**Issue by robeche** [DualSPHysics/DesignSPHysics#19]
Hello all and thanks for this awesome software.

I used DesignSPhysics some months ago with some succes. Now I am moving to another computer and downloaded everything again and i can't make it work.

First of all, when I load the plugin i do not receive any warning as you mention in the help. I setup the plugin with the corresponding paths. I have prepared a case with a simple box filled with water and hole... I save everything and click on Run GenCase, but nothing happens and the Run button stays disabled...

Can you help me somehow?

Kind regards

Roberto

**Comment by zlotny** [comment]
Hi Roberto. That seems like an error while trying to execute GenCase.

Can you enable the Report View within FreeCAD (View -> Panels -> Report View) and try again? It should display errors there once you try to run GenCase. 

Can you check which step of those you've done throw errors and paste here the error from the report view? Thank you!

**Comment by zlotny** [comment]
There was a new version of DesignSPHysics released just today that fixes a ton of errors. If you keep getting this problem please try the new version.
