### ISSUE TITLE
Cannot run the installer

### ISSUE THREAD

**Issue by bladomas** [DualSPHysics/DesignSPHysics#2]
When I try to execute the installer I get this error: (I'm using centos 7)

Traceback (most recent call last):
  File "PyInstaller/loader/rthooks/pyi_rth_qt4plugins.py", line 43, in <module>
ImportError: No module named PyQt4.QtCore
[19337] Failed to execute script pyi_rth_qt4plugins

I have installed PyQt4 and PyInstaller separately but I still get the same error. Anyone that can give advice?

**Comment by zlotny** [comment]
Are you running the installer executable from a release or executing the install via python with the cloned repository?

The Qt libs that the installer uses are from PySide, not PyQt4, maybe that could fix the issue. However, the purpose of the installer is precisely not having to install dependencies, hence my first question.

If none of the above was useful, please check the readme in the sections about installing the software, as it contains manual instructions as well.

**Comment by bladomas** [comment]
I had downloaded it from http://design.sphysics.org/, I have only now noticed it differs from the files provided here. I had unzipped and executed the .exe file.
Now, I downloaded the zip file from github, went to the installer folder and executed .py file. The error I get is:

./installer.py: line 10: $'DesignSPHysics Installer.\r\n\r\nThis file spawns a Qt window that installs DSPH files\r\ninto FreeCAD\'s default Macro directory.\r\n\r\nThis script is meant to use with pyinstaller to generate\r\na simple standalone executable for release.\r\n\r\n\r': command not found
./installer.py: line 11: $'\r': command not found
