### ISSUE TITLE
Various Issues

### ISSUE THREAD

**Issue by JabirSS** [DualSPHysics/DesignSPHysics#20]
Dear developers,

I've been trying to runDesignSPHysics on Linux Mint 19 with FreeCAD 0.18.3 and I faced the following two issues;

1- There was an issue in user/.FreeCAD/Mod/DesignSPHysics/ds_modules/utils.py file, line 82 where you compare the FreeCAD version number to the supported one. I'm not that familiar with python so I'm not sure what's the source of the issue, but for some reason, it had a problem converting the string to an int and I had to change the line to `version_num = 18`.

2- Pressing the "Add to DSPH Simulation" button does not do anything, I can't see any error messages neither in my terminal or in the Report view. Any ideas?

Many thanks in advance

**Comment by zlotny** [comment]
Hi there! Thanks for reporting those issues.

What version of designspysics are you using? It is the latest release? (You can find the version number at the top of the DesignSPHysics panel, within FreeCAD.

**Comment by JabirSS** [comment]
@zlotny,

Thank you for your quick response. I am using the version 0.5.1.1906-4, which I believe is the latest version.

**Comment by zlotny** [comment]
Can you download and try the latest development version? 

You can download it from here: https://github.com/DualSPHysics/DesignSPHysics/tree/develop

Check the readme below on how to install it. To clone/download it you can do it there:
![image](https://user-images.githubusercontent.com/6155245/65580695-785ee580-df7a-11e9-8be8-38693087b79b.png)

Hope that solves your error.

**Comment by JabirSS** [comment]
The development version works just fine! Thanks a lot.
