### ISSUE TITLE
Some questions about .stl model position offsets and mdbc

### ISSUE THREAD

**Issue by Jun-005** [DualSPHysics/DesignSPHysics#203]
Dear all,
  I'm a beginner of DualSPHysics. I'm sorry if my question struck you as cheap. 
  I'm now trying to run a simulation of the effects of a landslide on a pipeline, but after when I'm done building the three STL models and aligning them as best I can in FreeCad. 
![q11](https://github.com/DualSPHysics/DesignSPHysics/assets/94217354/5b95def6-1d92-44b5-b009-6ca45a2cd6ce)

When I run GenCase in FreeCAD and then I look at the run results in Paraview, I find that the positions of the three stl model particles are drastically shifted, which prevents me from proceeding to the next step, can anyone tell me what's going on and how to fix it?
![q12](https://github.com/DualSPHysics/DesignSPHysics/assets/94217354/6df226e0-a749-41dc-9d9f-626ab59474ee)
Also, I have another question, if I want to use the mbdc method during this simulation. How should I do it so as to avoid such error as below?
![q2](https://github.com/DualSPHysics/DesignSPHysics/assets/94217354/594abafd-30fc-4b58-8cdf-8b01f08308e9)

Please tell me how can I solve these problems. I'd appreciate it! And here is my Email: junhzh87@gmail.com

**Comment by Zahramht** [comment]
> Dear all, I'm a beginner of DualSPHysics. I'm sorry if my question struck you as cheap. I'm now trying to run a simulation of the effects of a landslide on a pipeline, but after when I'm done building the three STL models and aligning them as best I can in FreeCad. ![q11](https://private-user-images.githubusercontent.com/94217354/327993393-5b95def6-1d92-44b5-b009-6ca45a2cd6ce.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTY4OTUsIm5iZiI6MTcxNTU5NjU5NSwicGF0aCI6Ii85NDIxNzM1NC8zMjc5OTMzOTMtNWI5NWRlZjYtMWQ5Mi00NGI1LWIwMDktNmNhNDVhMmNkNmNlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEwMzYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYjIwODNkMzk2N2RiMjgyY2IwZTRiNmZlZWZjY2Y4MjM2YTZmOGM5ODVhNDM1ODAxMzk3NTE2MzhlMDQ0YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vE_ZW0SGm0PuX_s-L36P7g43mO5uwKB2yNs4TsK4yWo)
> 
> When I run GenCase in FreeCAD and then I look at the run results in Paraview, I find that the positions of the three stl model particles are drastically shifted, which prevents me from proceeding to the next step, can anyone tell me what's going on and how to fix it? ![q12](https://private-user-images.githubusercontent.com/94217354/327993505-6df226e0-a749-41dc-9d9f-626ab59474ee.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTY4OTUsIm5iZiI6MTcxNTU5NjU5NSwicGF0aCI6Ii85NDIxNzM1NC8zMjc5OTM1MDUtNmRmMjI2ZTAtYTc0OS00MWRjLTlkOWYtNjI2YWI1OTQ3NGVlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEwMzYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNzZjMDZhYTJhZDNjMjAyNzg4OTcyZGIyZTM4OTQ0ZDBiYWRkMmI0MzY4Y2ExMDE2NDA2YzMwOWQwZjgyNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lypYC_b5u-vN13yf_mgsZTjOO_QryKEtJSPugFAASl4) Also, I have another question, if I want to use the mbdc method during this simulation. How should I do it so as to avoid such error as below? ![q2](https://private-user-images.githubusercontent.com/94217354/327993668-594abafd-30fc-4b58-8cdf-8b01f08308e9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTY4OTUsIm5iZiI6MTcxNTU5NjU5NSwicGF0aCI6Ii85NDIxNzM1NC8zMjc5OTM2NjgtNTk0YWJhZmQtMzBmYy00YjU4LThjZGYtOGIwMWYwODMwOGU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEwMzYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2NmVhNmFjZTRlYjhiNGQ4YjE2ZTVkZjhkNzM3ZmNlZjgyNzQxMzAzNWY2MzUzMDMxMGIxM2IwZjg0N2EyZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GCNaeaOlBCsrT4lWDltLVW4Kc_g-6k-DI_kuluvK5e4)
> 
> Please tell me how can I solve these problems. I'd appreciate it! And here is my Email: [junhzh87@gmail.com](mailto:junhzh87@gmail.com)

Hi, 
I have also tried to implement mDBC with my 3D model as an STL, however, in the end, I ended up with DBC.
As far as I know, you should use XML files directly to implement mDBC on STL.
check this file from Professor Crespo who explained about mDBC and normal vectors. I hope that helps. https://drive.google.com/drive/folders/1XV1eoxFD-PvBkAieAyavcDsDeD1wtDLJ?usp=sharing

**Comment by 258458** [comment]
me too。

**Comment by Jun-005** [comment]
First of all, thanks for your reply and my apologies that I'm just now seeing the message.&nbsp;
If it's convenient, could you please repost the link to your reference document, which is the professor's help document for mDBC?





旁观者
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "DualSPHysics/DesignSPHysics"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月13日(星期一) 晚上6:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DualSPHysics/DesignSPHysics] Some questions about .stl model position offsets and mdbc (Issue #203)





  
Dear all, I'm a beginner of DualSPHysics. I'm sorry if my question struck you as cheap. I'm now trying to run a simulation of the effects of a landslide on a pipeline, but after when I'm done building the three STL models and aligning them as best I can in FreeCad. 
 
When I run GenCase in FreeCAD and then I look at the run results in Paraview, I find that the positions of the three stl model particles are drastically shifted, which prevents me from proceeding to the next step, can anyone tell me what's going on and how to fix it?  Also, I have another question, if I want to use the mbdc method during this simulation. How should I do it so as to avoid such error as below? 
 
Please tell me how can I solve these problems. I'd appreciate it! And here is my Email: ***@***.***
  
Hi,
 I have also tried to implement mDBC with my 3D model as an STL, however, in the end, I ended up with DBC.
 As far as I know, you should use XML files directly to implement mDBC on STL.
 check this file from Professor Crespo who explained about mDBC and normal vectors. I hope that helps. https://drive.google.com/drive/folders/1XV1eoxFD-PvBkAieAyavcDsDeD1wtDLJ?usp=sharing

**Comment by 258458** [comment]
> 首先，感谢您的回复，我很抱歉我刚刚看到这条消息。 如果方便的话，您能否重新发布您的参考文档的链接，这是教授对 mDBC 的帮助文档？ 旁观者 ***@***.*** &nbsp;
> […](#)
> ------------------ 原始邮件 ------------------ 发件人： “DualSPHysics/DesignSPHysics” ***@***.***>; 发送时间：&nbsp;2024年5月13日(星期一) 晚上6:58 @***.***>; @***.******@***.***>; 主题：&nbsp;回复：[DualSPHysics/DesignSPHysics] 关于 .stl 模型位置偏移和 mdbc 的一些问题（问题 #203） 亲爱的大家，我是DualSPHysics的初学者。如果我的问题让你觉得便宜，我很抱歉。我现在正在尝试对滑坡对管道的影响进行模拟，但是在我完成构建三个 STL 模型并在 FreeCad 中尽可能地对齐它们之后。 当我在FreeCAD中运行GenCase，然后在Paraview中查看运行结果时，我发现三个stl模型粒子的位置发生了急剧的变化，这使我无法进行下一步，谁能告诉我发生了什么以及如何修复它？另外，我还有另一个问题，如果我想在此模拟中使用mbdc方法。我应该怎么做才能避免以下错误？ 请告诉我如何解决这些问题。我将不胜感激！这是我的电子邮件：***@***.*** 你好 我还尝试将我的 3D 模型作为 STL 实现 mDBC，但最终，我最终选择了 DBC。 据我所知，您应该直接使用XML文件在STL上实现mDBC。 查看 Crespo 教授的此文件，他解释了 mDBC 和正态向量。我希望这会有所帮助。https://drive.google.com/drive/folders/1XV1eoxFD-PvBkAieAyavcDsDeD1wtDLJ?usp=sharing—— 直接回复此电子邮件，在 GitHub 上查看或取消订阅。 您收到此消息是因为您创作了线程。消息 ID：***@***.***>

that's solution method?

**Comment by 258458** [comment]
this   Url  not find in emil
