### ISSUE TITLE
'PermissionError':Exception value: [Errno 1] Operation not permitted: './dualsphysics/bin/DualSPHysics5.2_linux64'

### ISSUE THREAD

**Issue by WANG-KUI-TJU** [DualSPHysics/DesignSPHysics#205]
# description
when i click `Execution Parameters`,error coming.
![图片](https://github.com/DualSPHysics/DesignSPHysics/assets/58095469/a499df87-6cc6-4071-89e9-dc968bc1fc31)
![图片](https://github.com/DualSPHysics/DesignSPHysics/assets/58095469/540ffecf-c39e-47a2-a0fc-2da122cb6bdf)

# Error
```
DesignSPHysics version: 0.7.0 (15-09-2023)
Platform: Linux-5.15.0-105-generic-x86_64-with-glibc2.14
FreeCAD Version: 0.21.2
Exception type: <class 'PermissionError'>
Exception value: [Errno 1] Operation not permitted: './dualsphysics/bin/DualSPHysics5.2_linux64'
Traceback:
```
```
 ‘File "/usr/share/freecad/Mod/DesignSPHysics/mod/widgets/dock/dock_configuration_widget.py", line 84, in on_execparams_button_presed
    ExecutionParametersDialog(parent=get_fc_main_window())
  File "/usr/share/freecad/Mod/DesignSPHysics/mod/widgets/execution_parameters_dialog.py", line 164, in __init__
    densitydt_option_list = [__('None'), __('Molteni'), __('Fourtakas'), __('Fourtakas (Full)')] if Case.the().executable_paths.supports_ddt_fourtakas() else ['None', 'Molteni']
  File "/usr/share/freecad/Mod/DesignSPHysics/mod/dataobjects/executable_paths.py", line 77, in supports_ddt_fourtakas
    return bool(get_executable_info_flag(self.dsphysics)["Features"]["DDT_Fourtakas"])
  File "/usr/share/freecad/Mod/DesignSPHysics/mod/executable_tools.py", line 53, in get_executable_info_flag
    ensure_process_is_executable_or_fail(executable)
  File "/usr/share/freecad/Mod/DesignSPHysics/mod/executable_tools.py", line 82, in ensure_process_is_executable_or_fail
    chmod(cli_path, st.st_mode | unix_stat.S_IEXEC)
```
# try to solve
- 1.Use command `ls -l /path/to/dualsphysics/bin/DualSPHysics5.2_linux64` and find that `ls -l /path/to/dualsphysics/bin/DualSPHysics5.2_linux64`,so its not a question of access
- 2.then i ues command `./dualsphysics/bin/DualSPHysics5.2_linux64 --help`,then
![图片](https://github.com/DualSPHysics/DesignSPHysics/assets/58095469/4ab308c8-849b-467f-be59-94e80ad6a340)
i  use command `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/dualsphysics/bin`,still same error

# how to solver this problem

**Comment by WANG-KUI-TJU** [comment]
1.Use command `ls -l /path/to/dualsphysics/bin/DualSPHysics5.2_linux64` and find that `-rwxrwxrwx 1 root root 47341728 5月  21 22:21 ./dualsphysics/bin/DualSPHysics5.2_linux64`,so its not a question of access.

**Comment by imestevez** [comment]
Could it be that you are trying to load a case generated by an older version of DesignSPHysics?
