### ISSUE TITLE
 ValueError in DesignSPHysics: Total particles substring not found

### ISSUE THREAD

**Issue by erickrogenes** [DualSPHysics/DesignSPHysics#208]
Hi everyone,

I'm experiencing an issue with DesignSPHysics where I receive the following error message:

Traceback (most recent call last):
File "C:\Users\rogen\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\widgets\dock\dock_pre_processing_widget.py", line 269, in on_execute_gencase
total_particles_text = output[output.index("Total particles: ")
.index(" (bound=")]
ValueError: substring not found

I am using the latest version of DualSPHysics and designsphysics.

Has anyone encountered this issue before or have any suggestions on how to fix it?

Thanks in advance for your help!

![Captura de tela 2024-06-12 124902 PNG](https://github.com/DualSPHysics/DesignSPHysics/assets/114227385/5329f32e-87e7-4235-9cf4-5609cc46a2f1)

**Comment by imestevez** [comment]
Please check that the path where you are executing the case does not contain spaces or special characters.

**Comment by erickrogenes** [comment]
It was that, thank you!!
