### ISSUE TITLE
Regarding Herschel-Bulkley-Papanastasiou model implementation for my non-Newtonian fluid.

### ISSUE THREAD

**Issue by BenjaminBasumatary** [DualSPHysics/DesignSPHysics#211]
I can't find any option to utilize the HBP model for the analysis of my non-Newtonian fluid. I would greatly appreciate if you could guide me or let me know if the present model doesn't support so. In that case can you guide me to the version addressing the issue.

**Comment by imestevez** [comment]
Hello, that functionality is not available through DesignSPHysics yet. You can use it directly from the DualSPHysics package [https://dual.sphysics.org/downloads/](https://dual.sphysics.org/downloads/). In this package you will find examples in the folder `DualSPHysics_v5.2/examples/mphase_nnewtonian`
