### ISSUE TITLE
Filling a tank with inletoutlet examples

### ISSUE THREAD

**Issue by matte-giuf** [DualSPHysics/DesignSPHysics#212]
Hi everyone, I was trying to fill a cylindrical tank with a coaxial source but I'm having difficulties.
I am trying to follow the examples given in the inletoutlet folder, but when I place the source, the program gives me the following error ‘there are inout fluid or boundary particles too close to inout particles.’

I try moving the source but the problem persists.

How can I solve it?

Thank you

**Comment by panyue1359** [comment]
Try setting layers to 1, and make sure the direction vector is (0, 1, 0) or (0 ,-1, 0)

**Comment by matte-giuf** [comment]
> Try setting layers to 1, and make sure the direction vector is (0, 1, 0) or (0 ,-1, 0)

Thank you so much for the tip.

I've tried to setting layers to 1 and I was able to direct the flow the way I want.
