### ISSUE TITLE
Is BoundaryVTK available in  DesignSPHysics now? or any other way to show stl mesh

### ISSUE THREAD

**Issue by samcatfantasy** [DualSPHysics/DesignSPHysics#215]
Is BoundaryVTK available in  DesignSPHysics now ? or there are any other ways to show whole moving or floating chrono stl object mesh(not particles or points) in paraview or Blender.Thanks for help.

**Comment by jmdalonso** [comment]
You can always use the post-processing tools directly on the command line.
The DualSPHysics full release package (available on https://dual.sphysics.org/downloads/) includes more than 100 complete examples including the use of the post-processing tools.
