### ISSUE TITLE
Wrong viscosity??

### ISSUE THREAD

**Issue by matte-giuf** [DualSPHysics/DesignSPHysics#216]
Hello, everyone,

I am currently studying the phenomenon of sloshing on a container, which moves in circular motion; first on a circumference, then at a point it changes direction, along a smaller circumference, describing a kind of ‘s’; I have tried to reproduce the phenomenon in DualSPHysics, but as you can see from these comparison frames, the sloshing phenomenon of the SPH model seems to be more contained, despite having entered the correct data. I have tried changing the viscosity value, even switching from Artificial to Laminar+SPS, but the model does not change. What am I doing wrong?
I have also tried changing the ViscoBoundFactor, but nothing happens.

Thanks in advance.

![confronto_testbenc_SPH](https://github.com/user-attachments/assets/09f01223-e84f-4d03-be02-d45b89a2bffa)

**Comment by imestevez** [comment]
You may check the the setup of the container. Which boundary conditions are you using?

**Comment by matte-giuf** [comment]
> You may check the the setup of the container. Which boundary conditions are you using?

I use the mDBC conditions, and now I try some viscosity value ad I find the correct way. Thanks
