### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by dipta005** [DualSPHysics/DesignSPHysics#217]
Hello, 
I just installed this macro on Freecad. But after loading, this is the error that showing:

08:42:27  [DesignSPHysics] main.py:94 -> Invalid document environment found. Disabling case-related tools.
![image](https://github.com/user-attachments/assets/6e70e27b-5be8-46da-a07c-876a202399e0)

**Comment by qoimzslm** [comment]
Hi, may I know how do you solve the problem of "invalid document environment found"?
In this case I am using LINUX. Thank you for your answer
