### ISSUE TITLE
Is DesignSPHysics ready for FreeCAD v1.0 release ?

### ISSUE THREAD

**Issue by luzpaz** [DualSPHysics/DesignSPHysics#218]
* https://github.com/FreeCAD/FreeCAD-addons/issues/305

**Comment by kwahoo2** [comment]
DesignSPHysics thinks that FreeCAD 1.0 is too low version:
![obraz](https://github.com/user-attachments/assets/3d84d273-51f6-4eb7-a4be-e6f212bcde94)

Here is the culprit:
https://github.com/DualSPHysics/DesignSPHysics/blob/master/mod/freecad_tools.py#L45

`FreeCAD.Version()[0] + FreeCAD.Version()[1]` returns 10, while min version constant is 018.

After making a workaround for this, there is another issue:
`12:10:43  pyException: Traceback (most recent call last):
  File "/home/adi/.local/share/FreeCAD/Macro/DesignSPHysics.FCMacro", line 25, in <module>
    boot()
  File "/home/adi/.local/share/FreeCAD/Mod/DesignSPHysics/mod/main.py", line 149, in boot
    fc_object_tree: QtGui.QTreeWidget = get_fc_main_window().findChildren(QtGui.QSplitter)[0].findChildren(QtGui.QTreeWidget)[0]
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
<class 'IndexError'>: list index out of range`

**Comment by luzpaz** [comment]
@imestevez :point_up_2:

**Comment by luzpaz** [comment]
@imestevez ping

**Comment by imestevez** [comment]
It is not comptatible with FreeCAD `=>v1.0` yet.

**Comment by luzpaz** [comment]
Is there an ETA ?

**Comment by imestevez** [comment]
The latest version is already compatible with FreeCAD v1.0
