### ISSUE TITLE
Importing STL files

### ISSUE THREAD

**Issue by AhmedSalih3d** [DualSPHysics/DesignSPHysics#22]
There seems to be a bug using; https://design.sphysics.org/ when working in FreeCad on Windows 10, and then trying to use .stl files. The issue was immediately resolved when I tried a development build from here.

Kind regards

**Comment by zlotny** [comment]
Hi, thanks for the notice! I forgot to answer you :(

I've released a new version today that fixes all errors related with importing external geometry, and it's now on the master branch.

Thank's for letting me know!
