### ISSUE TITLE
Failed to select a valid CellCode

### ISSUE THREAD

**Issue by Mikasa-0** [DualSPHysics/DesignSPHysics#220]
Hi everyone,
Please, I need your help regarding what could probably be wrong here and what should be done:
Exception (jSphCpuSingle::SelecDomain)at DualSPHysics/source/JSph. cpp:1825
Text: Failed to select a valid CellCode for 72169x18043x39693 cells(CellMode=Fu11).
Thanks.
![82d579b19b8d662594ac4e0c0be1c86](https://github.com/user-attachments/assets/f5832cc0-5060-41f2-b9d7-92cc1c0cad19)

**Comment by imestevez** [comment]
Check the size of the domain you are defining; it may be too large to be generated

**Comment by qoimzslm** [comment]
Hello, I have the same issue as above. when I set inter-particle distance 0.01 m it is work properly. I try to lower interparticle distance to 0.0001 and 0.005. However, I get the error stating like this. Is there any comments why this is happen? Also, what is the matter of inter-particle distance in DesignSPHysics? Is that the parameters that influence Kernel function?
<img width="900" alt="error" src="https://github.com/user-attachments/assets/1c9f5d8b-5e66-4169-b89f-c1fdc5e9ebe9">

**Comment by imestevez** [comment]
The dp is the initial interparticle distance, so it indicates the resolution. What you have to check is the size of the domain in `Case Limits` on the left panel
