### ISSUE TITLE
How to choose CPU_Blocksize in DesignSPHysics?

### ISSUE THREAD

**Issue by JUN-D228** [DualSPHysics/DesignSPHysics#221]
I am a beginner. I saw mention of blocksize in section 5.5 of the user manual (DualSPHysic)：

“An important novelty since v4.0 is the determination of the optimum Blocksize for CUDA kernels that excute particle interaction......”

 but  I would like to ask how to set the blocksize in the DesignSPHysics.

**Comment by imestevez** [comment]
You have to select the blocksize in the DualSPHysics code [https://github.com/DualSPHysics/DualSPHysics](https://github.com/DualSPHysics/DualSPHysics), compile it and then, use the new executable within DesignSPHysics
