### ISSUE TITLE
Error_BoundaryOut.vtk

### ISSUE THREAD

**Issue by qoimzslm** [DualSPHysics/DesignSPHysics#224]
Hello, I have an issue about the error of boundary. Anybody know how to fix these kind of problem? Thank you in advance
<img width="247" alt="image" src="https://github.com/user-attachments/assets/bcc8d938-1935-433a-9cd9-ae57d0f31626">

**Comment by luzpaz** [comment]
Can you upload a sample file ? Compress it (or rename the file extension to zip) and drag/drop it into github textbox here
Also please add you full [About](https://wiki.freecad.org/About) info

**Comment by imestevez** [comment]
As it shows the text error, a boundary particle was excluded due to the velocity. Error_BoundaryOut.vtk file gives information about which particles were excluded, so you can use that information to fix your setup.

**Comment by 258458** [comment]
I'm simulating a cylindrical bucket rotation to create a vortex, but I imported the bucket model and set the appropriate simulation size, but I get an error when I run it, and the boundary particles are out of range, I want to ask what is the reason for this?
![image](https://github.com/user-attachments/assets/50ba1b64-4fde-4dd0-bb1b-a04d1f8e0280)

**Comment by 258458** [comment]
![image](https://github.com/user-attachments/assets/2311e7e6-6b16-46e4-99e7-976970e4770b)
this is error-BoundaryOut.vtk

**Comment by 258458** [comment]
`This is my case file

**Comment by 258458** [comment]
[tong.zip](https://github.com/user-attachments/files/17954253/tong.zip)

**Comment by imestevez** [comment]
Same issue is discussed here: https://github.com/DualSPHysics/DesignSPHysics/issues/228
