### ISSUE TITLE
How to export floating VTK files with smooth surfaces instead of particles?

### ISSUE THREAD

**Issue by eorliiy** [DualSPHysics/DesignSPHysics#225]
Hi, I am using the floating  feature of the bound, but all the bound vtk files I exported are in particle form, how can I export the bound vtk file that looks like the normal model instead of the particle from?

**Comment by imestevez** [comment]
That feature is not included in DesignSPHysics. You can use the postprocessing tools directly from the package of DualSPHysics where you will find information and examples https://dual.sphysics.org/downloads/
