### ISSUE TITLE
Ordering of objects 

### ISSUE THREAD

**Issue by AhmedSalih3d** [DualSPHysics/DesignSPHysics#23]
How should ordering of objects be done?

I've tried having fluid at top and then solids at bottom, and then it works

If I then have fluid at top, then change the ordering of solids, the particles are all wrong

If I then have fluid at bottom and objects at top it is still wrong

Why is this important, when none of my objects are overlapping?

Kind regards

**Comment by zlotny** [comment]
Hi there. Well, this is not technically an issue related to the development but I'll try to answer it the best I can with the knowledge I have.

Every object in the scene is going to be converted to particles by GenCase. GenCase allocates particles in a 3d matrix in where each point is a particle.

When you have 2 objects that occupy the same space GenCase will first put particles in the space for the first in the list, then the second, potentially overriding the first.

As you imagine you can't have 2 particles in one place of the 3d matrix, so each time GenCase draws an object (following that list order) it overrides whatever was in that space, being empty or not.

I hope that makes sense. If you have doubts at how DualSPHysics works please refer to the forums to ask: https://forums.dual.sphysics.org/

**Comment by AhmedSalih3d** [comment]
Thanks for your comment @zlotny , the behaviour seems to me just to be different than working with XML files directly. Imagine I have a case like this;

![image](https://user-images.githubusercontent.com/36305327/65945949-5a3f2c80-e435-11e9-9e66-d2f398a2b8de.png)

Non of the objects are overlapping and all are inside the red domain in Freecad. The walls are cut from two boxes in Freecad, the water is just a box and the ball is just a sphere inside Freecad. None of the objects are overlapping, so I just can't understand why it would be so important. Maybe FreeCad is filling the particles out in some specific way. If you consider this to be normal behaviour, then there is no problem, but for me it is very unintuitive having to "guess" placement of objects, and this has to me only been a problem using Freecad and not the xml.

But of course I might be mistaken.

Kind regards

**Comment by AhmedSalih3d** [comment]
Thank you very much for your thorough explanation! Also you are very right, I have been a bit too vague about how the xml is setup etc. At the end of the week I will be sure to provide the different xml's based on different ordering and see if I can explain what goes on.

Also thanks for the last PS2, I thought the goal with FreeCAD was to completely forget about the xml files, but I see the point, as this being a tool to use, before doing all the fancy work in the xml directly.

I will try to share the files / results of particles as soon as possible, hopefully in this week.

Kind regards

**Comment by AhmedSalih3d** [comment]
I cannot get the case to work right now on the newer version of DesignSPHysics. I tested on a earlier version and everything did as I would expect. I will close this issue since I am not able to provide files which will help determine if there is a bug or not.

Kind regards
