### ISSUE TITLE
Fill mode option was disabled in the newly created geometry

### ISSUE THREAD

**Issue by qoimzslm** [DualSPHysics/DesignSPHysics#231]
Hi, I would like to create my own solid geometry, for example, a solid triangle. I am trying to create in some ways.
1. Through the **sketcher** menu, I make a 2D triangle shape and then extrude it to 3D.
2. Through the **part** menu, I create a solid cube and do a chamfer to make it triangular shape rather than a cube.
However, when I try to add the solid object by the above way to DSPH simulation, all of them are formed as "Face" in the **Fill mode** feature, and I'm unable to change it a solid object. How can I create a solid/full object with my design shape in DesignSPHysics?
<img width="708" alt="image" src="https://github.com/user-attachments/assets/d17b81c9-89fd-49d0-a5b9-83cd69c56f2f">

This question has similar issue with case #201 which has not yet close
Thank you very much for your reply.

**Comment by Jiaxi-Huang** [comment]
Same quetions
