### ISSUE TITLE
Cannot add objects to DSPH simulation

### ISSUE THREAD

**Issue by MrMampfred** [DualSPHysics/DesignSPHysics#25]
In the newest version 
"DesignSPHysics 0.6.0.1911-07-2"
the button for adding an object to the simulation, which is usually in the bottom left corner of the screen, is not available. This means that there is no way to add any objects to the simulation.
It was tested with simple cubes and also with imported meshes.
The used FreeCAD version is 0.18

**Comment by zlotny** [comment]
Hello. Thanks for your report.
I've been unable to replicate the error that you explained. Either with FreeCAD objects or imported meshes the button seems to appear to me.

Can you try to replicate the issue with the Report View open (View -> Panels -> Report View) to see if it spawns any errors?

I assume DesignSPHysics didn't spawn any "general application error" dialog as you didn't provide any exception information. Weird :S

Thanks!

**Comment by MrMampfred** [comment]
Ok, I opened the report window and tried again.
I get an error upon starting the macro:

`Traceback (most recent call last):
  File "C:/Users/SebastianPC/AppData/Roaming/FreeCAD/Macro/DesignSPHysics.FCMacro", line 26, in <module>
    import mod.main  # pylint: disable=unused-import
  File "C:\Users\SebastianPC\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\main.py", line 110, in <module>
    fc_object_tree.itemSelectionChanged.connect(on_tree_item_selection_change)
<class 'AttributeError'>: 'NoneType' object has no attribute 'itemSelectionChanged'`

Seems I didn't notice that the first time, sorry for that.
I also tried on another PC and got the same issue.

**Comment by FlorianEnnemoser** [comment]
Hello, 
I've had the same error, FreeCAD version 0.18 and current DesignSPHysics Master Branch.
I fixed it by changing my FreeCAD Language from German to English and then reloaded the macro. 
Hope it helps!

**Comment by zlotny** [comment]
@FlorianEnnemoser I’ve been thinking that issue for a while and your comment clicked the problem in. The app searches for the FreeCAD Tree Widgets to find the one containing the object list so we can subscribe to their signals. 

I’m assuming that the “name” which we try to match to find it changes depending on the language.

I’ll fix it tomorrow as soon as possible. Thanks for the pointer!

**Comment by MrMampfred** [comment]
Yes thank you very much, 
changing the language indeed fixed the issue.

**Comment by zlotny** [comment]
The issue is now solved on master. I've changed the way in which DesignSPHysics finds the treeview so now it is independent on the language.

Thanks for the help!
