### ISSUE TITLE
Simple and double precision interchanged

### ISSUE THREAD

**Issue by MrMampfred** [DualSPHysics/DesignSPHysics#26]
I think I found a little bug in the execution parameters:

The values in the XML-file
when you select simple precision:
`<parameter key="PosDouble" value="1"` -->double precision
when you select double precision:
`<parameter key="PosDouble" value="0"` -->simple precision

![image](https://user-images.githubusercontent.com/29656295/68763381-94950f80-0618-11ea-87a2-a7fb54914649.png)

Maybe the text of the two options could just be swapped as I think it makes most sense to have simple precision as the first option for a chronological order.

The third option works fine.

**Comment by zlotny** [comment]
Indeed, they're swapped out :^)

Going to fix it right now.

**Comment by zlotny** [comment]
Fixed on master at e0df6fe3a5f5e9332a33bc4213b4d170a8fc7ee2

Thank you so much!

PS: Loving the new deploy/install procedure with the addon manager. Before that was fully cooked by the FreeCAD team I would have to custom make a package or you would need to download/clone/pull the new version :)
