### ISSUE TITLE
Periodicity not working

### ISSUE THREAD

**Issue by MrMampfred** [DualSPHysics/DesignSPHysics#27]
I got one more for you, but then I think I am done for the moment ^^

Periodicity settings from the execution parameters are not written into the XML file.

PS: I just wanted to say thank you for your great work (and quick responses), this addon makes it so much easier to work with DualSPHysics :D

**Comment by zlotny** [comment]
Ouch! That's 100% my fault. It got lost on the refactor of the XML rendering engine.

Thank you so much for checking out the options and finding bugs, it really, really helps a lot.

I'll have a look on that tomorrow.

**Comment by zlotny** [comment]
Issue is fixed on commit c37d9c943f1ad9eb112f1c249b2cbd33dea31d09

Thanks again for reporting the issue!
