### ISSUE TITLE
Paddle without range of motion particles valid

### ISSUE THREAD

**Issue by kwadl** [DualSPHysics/DesignSPHysics#29]
I was able to get the 2D wave tank example running in 0.5.1, however, faithfully replicating the case in 0.6.0.1911-07-2 leads to the error below. The case looks fine in ParaView, and the settings for the piston are exactly the same, so haven't been able to get to the bottom of it. I've attached the case. BTW, really appreciate this project.

==========================
LoadDsphConfig> .../dualsphysics/bin/DsphConfig.xml
[Select CUDA Device]
[CUDA Capable device(s)]
  Detected 1 CUDA Capable device(s)
  CUDA Driver Version / Runtime Version: 10.1 / 9.2
 
Device 0: "GeForce GTX 1050 Ti"
  CUDA Capability Major....: 6.1
  Global memory............: 4096 MBytes
  CUDA Cores...............: 768 ( 6 Multiprocessors, 128 CUDA Cores/MP)
  GPU Max Clock rate.......: 1620 MHz (1.62 GHz)
  Memory Clock rate........: 3504 Mhz
  Memory Bus Width.........: 128-bit
  L2 Cache Size............: 1024 KBytes
  Constant memory..........: 64 KBytes
  Shared memory per block..: 48 KBytes
  Registers per block......: 65536
  Maximum threads per MP...: 2048
  Maximum threads per block: 1024
  Concurrent copy and kernel execution....: Yes with 5 copy engine(s)
  Run time limit on kernels...............: Yes
  Integrated GPU sharing Host Memory......: No
  Support host page-locked memory mapping.: Yes
  Device has ECC support..................: Disabled
  CUDA Device Driver Mode (TCC or WDDM)...: WDDM (Windows Display Driver Model)
  Device supports Unified Addressing (UVA): Yes
  Device PCI (Domain / Bus / location)....: 0 / 1 / 0
  Device supports P2P and RDMA............: No
 
[GPU Hardware]
Device default: 0  "GeForce GTX 1050 Ti"
Compute capability: 6.1
Memory global: 4096 MB
Memory shared: 49152 Bytes

[Initialising JSphGpuSingle  20-11-2019 16:40:30]
ProgramFile=".../dualsphysics/bin/DualSPHysics4.4_win64.exe"
ExecutionDir=".../freecad/Mod/DesignSPHysics"
XmlFile=".../waves_test/waves_test_out/waves_test.xml"
OutputDir=".../Desktop/waves_test/waves_test_out"
OutputDataDir=".../Desktop/waves_test/waves_test_out"
**Basic case configuration is loaded
**Special case configuration is loaded
Loading initial state of particles...
Loaded particles: 11097
MapRealPos(border)=(-0.101273,-0.00127279,-0.00127279)-(10.7913,0.00127279,0.676273)
MapRealPos(final)=(-0.101273,-0.00127279,-0.00127279)-(10.7913,0.00127279,0.676273)
**Initial state of particles is loaded
**2D-Simulation parameters:
CaseName="waves_test"
RunName="waves_test"
Simulate2DPosY=0
Symmetry=False
PosDouble="0: Uses and stores in single precision"
SvTimers=True
Boundary="DBC"
StepAlgorithm="Verlet"
VerletSteps=40
Kernel="Wendland"
Viscosity="Artificial"
Visco=0.010000
ViscoBoundFactor=0.000000
DensityDiffusion="None"
Shifting="None"
RigidAlgorithm="None"
FloatingCount=0
CaseNp=11097
CaseNbound=864
CaseNfixed=864
CaseNmoving=0
CaseNfloat=0
CaseNfluid=10233
PeriodicActive="None"
Dx=0.015
H=0.025456
CoefficientH=1.2
CteB=210214.281250
Gamma=7.000000
RhopZero=1000.000000
Cs0=38.3601
CFLnumber=0.200000
DtIni=0.000663602
DtMin=3.31801e-05
DtAllParticles=False
MassFluid=0.225000
MassBound=0.225000
Awen (Wendland)=859.567932
Bwen (Wendland)=-168847.218750
TimeMax=8
TimePart=0.025
Gravity=(0.000000,0.000000,-9.810000)
NpMinimum=864
RhopOut=True
RhopOutMin=700.000000
RhopOutMax=1300.000000
**Requested GPU memory for 11107 particles: 1.4 MB (0 times).
CellMode="2H"
Hdiv=1
MapCells=(214,1,14)
DomCells=(214,1,14)
DomCellCode="15_8_10"
 
BlockSize calculation mode: Fixed.
  BsForcesBound=128 (40 regs)
  BsForcesFluid=128 (52 regs)
 
**CellDiv: Requested gpu memory for 11661 particles: 0.1 MB.
**CellDiv: Requested gpu memory for 3120 cells (CellMode=2H): 0.0 MB.
 
RunMode="Pos-Single - Single-Gpu"
 
Particle summary:
  Fixed....: 864  id:(0-863)   MKs:3 (10-12)
  Moving...: 0
  Floating.: 0
  Fluid....: 10233  id:(864-11096)   MKs:1 (1)

Total particles: 11097 (bound=864 (fx=864 mv=0 ft=0) fluid=10233)
Total MK blocks: 4 (bound=3 (fx=3 mv=0 ft=0) fluid=1)
 
Wave paddles configuration:

*** Exception (JWavePaddleRegular::CheckConfig)
Text: Paddle without range of motion particles valid.

Finished execution (code=1).

[waves_test.zip](https://github.com/DualSPHysics/DesignSPHysics/files/3870331/waves_test.zip)

**Comment by zlotny** [comment]
Hi there. Thanks for reporting this issue. However this is currently a duplicated of issue #28 , which I already identifying and I'm now fixing. Please, check out that issue to know when I solve the issue.

By the way, in the case you provided in a zip the error was the same as in #28, this:
```
<objreal ref="13">
    <begin mov="1" start="0"/> 
    <mvnull id="1" />
 </objreal>
```
References  `13`. That number is supposed to be an MK bound, however DesignSPHysics is writing the real mk (mkbound + 11, mkfluid as is), so that's basically the bug.

I'm closing this issue for simplicity. Please check #28 

Thanks again for reporting error, this is really helpful as it is difficult to track all of this things by myself :)

**Comment by kwadl** [comment]
Thanks for the super quick reply! Should the case still run then if I manually modify the xml after running GenCase? (i.e. modify to ref="2"). I've tried that and it seems to generate the same error...

**Comment by zlotny** [comment]
Unfortunately no :(

GenCase generates binary data on disk (particle positions and information) based on the XML. When you press "Run" on DesignSPHysics, DualSPHysics is not using the XML, but the generated binary particles made by GenCase.

You can run GenCase from the command line, though. As you can see, if you press "Run GenCase" the window that appears shows you the command that was executed, so you can replicate that.

However, I'll be done with this patch in just 10 minutes, as I already fixed it and I'm commiting it to git right now :)

**Comment by zlotny** [comment]
The master branch is now updated with the last changes and fixes. Please upgrade your DesignSPHysics version and check that it now works correctly.

**Comment by julesangebault** [comment]
Hi, 
I think I have a similar issue.  I don't know how to fix it. 


 <DUALSPHYSICS5> Copyright (c) 2020 by
 Dr Jose M. Dominguez, Dr Alejandro Crespo,
 Prof. Moncho Gomez Gesteira, Prof. Benedict Rogers,
 Dr Georgios Fourtakas, Prof. Peter Stansby, Dr Ricardo Canelas,
 Dr Renato Vacondio, Dr Corrado Altomare, Dr Angelo Tafuni,
 Orlando Garcia-Feal, Dr Jose Gonzalez Cao

 EPHYSLAB Environmental Physics Laboratory, Universidade de Vigo
 School of Mechanical, Aerospace and Civil Engineering, University of Manchester

 DualSPHysics is free software: you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public License
 as published by the Free Software Foundation, either version 2.1 of
 the License, or (at your option) any later version.

 DualSPHysics is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with DualSPHysics. If not, see <http://www.gnu.org/licenses/>.


DualSPHysics5 v5.0.106 (03-05-2020)
====================================
LoadDsphConfig> .../bin/windows/DsphConfig.xml
[Select CUDA Device]
[CUDA Capable device(s)]
  Detected 1 CUDA Capable device(s)
  CUDA Driver Version / Runtime Version: 10.2 / 9.2
 
Device 0: "GeForce MX150"
  CUDA Capability Major....: 6.1
  Global memory............: 2048 MBytes
  CUDA Cores...............: 384 ( 3 Multiprocessors, 128 CUDA Cores/MP)
  GPU Max Clock rate.......: 1532 MHz (1.53 GHz)
  Memory Clock rate........: 3004 Mhz
  Memory Bus Width.........: 64-bit
  L2 Cache Size............: 512 KBytes
  Constant memory..........: 64 KBytes
  Shared memory per block..: 48 KBytes
  Registers per block......: 65536
  Maximum threads per MP...: 2048
  Maximum threads per block: 1024
  Concurrent copy and kernel execution....: Yes with 5 copy engine(s)
  Run time limit on kernels...............: No
  Integrated GPU sharing Host Memory......: No
  Support host page-locked memory mapping.: Yes
  Device has ECC support..................: Disabled
  CUDA Device Driver Mode (TCC or WDDM)...: WDDM (Windows Display Driver Model)
  Device supports Unified Addressing (UVA): Yes
  Device PCI (Domain / Bus / location)....: 0 / 1 / 0
  Device supports P2P and RDMA............: No
 
[GPU Hardware]
Device default: 0  "GeForce MX150"
Compute capability: 6.1
Memory global: 2048 MB
Memory shared: 49152 Bytes

[Initialising JSphGpuSingle  29-05-2020 00:52:31]
ProgramFile=".../bin/windows/DualSPHysics5.0_win64.exe"
ExecutionDir=".../FreeCAD/Mod/DesignSPHysics"
XmlFile=".../S3/S3_out/S3.xml"
OutputDir=".../S3/S3/S3_out"
OutputDataDir=".../S3/S3/S3_out"
XML-Vars (uservars + ctes): CaseName=["S3"]  Data2D=[0]  Data2DPosy=[0]  H=[0.311769]  B=[514286]  Gamma=[7]  Rhop0=[1000]  Dp=[0.15]  Gravity_x=[0]  Gravity_y=[0]  Gravity_z=[-9.81]  MassFluid=[3.375]  MassBound=[3.375]
XML-Vars (parameters): TimeMax=[3]  TimeOut=[0.025]
**Basic case configuration is loaded
**Special case configuration is loaded
Loading initial state of particles...
Loaded particles: 218628
MapRealPos(border)=(-0.075,-0.0155885,-0.0155885)-(49.875,9.76559,2.56559)
MapRealPos(final)=(-0.075,-0.0155885,-0.0155885)-(49.875,9.76559,2.56559)
**Initial state of particles is loaded
**3D-Simulation parameters:
CaseName="S3"
RunName="S3"
Symmetry=False
SavePosDouble=False
SaveFtAce=False
SvTimers=True
Boundary="DBC"
StepAlgorithm="Symplectic"
Kernel="Wendland"
Viscosity="Artificial"
  Visco=0.020000
  ViscoBoundFactor=0.000000
DensityDiffusion="None"
Shifting="None"
RigidAlgorithm="None"
FloatingCount=0
CaseNp=218628
CaseNbound=24671
CaseNfixed=21978
CaseNmoving=2693
CaseNfloat=0
CaseNfluid=193957
PeriodicActive="Axis-X"
PeriodicXinc=(-49.95,0,0)
Dx=0.15
H=0.311769
CoefficientH=1.2
CteB=514285.718750
Gamma=7.000000
RhopZero=1000.000000
Cs0=60
CFLnumber=0.200000
DtIni=0.00519615
DtMin=0.000259808
DtAllParticles=False
MassFluid=3.375000
MassBound=3.375000
Awen (Wendland)=13.786315
Bwen (Wendland)=-221.099182
TimeMax=3
TimePart=0.025
Gravity=(0.000000,0.000000,-9.810000)
NpMinimum=24671
RhopOut=True
RhopOutMin=700.000000
RhopOutMax=1300.000000
WrnPartsOut=True
**Requested GPU memory for 218638 particles: 35.0 MB (0 times).
CellMode="2H"
Hdiv=1
MapCells=(83,16,5)
DomCells=(83,16,5)
DomCellCode="14_11_8"
PosCellCode="13_10_9 (8192,1024,512)"
 
BlockSize calculation mode: Fixed.
  BsForcesBound=128 (42 regs)
  BsForcesFluid=128 (52 regs)
 
**JSphGpu: Requesting gpu memory for 230136 particles: 36.9 MB.
**CellDiv: Requested gpu memory for 234428 particles: 1.8 MB.
**CellDiv: Requested gpu memory for 7055 cells (CellMode=2H): 0.1 MB.
 
RunMode="Pos-Cell - Single-Gpu"
 
Particle summary:
  Fixed....: 21978  id:(0-21977)   MKs:1 (10)
  Moving...: 2693  id:(21978-24670)   MKs:1 (11)
  Floating.: 0
  Fluid....: 193957  id:(24671-218627)   MKs:1 (2)

Total particles: 218628 (bound=24671 (fx=21978 mv=2693 ft=0) fluid=193957)
Total MK blocks: 3 (bound=2 (fx=1 mv=1 ft=0) fluid=1)
 
Wave paddles configuration:

*** Exception (JWavePaddleRegular::CheckConfig) at ..\Source\Source_JWaveGen\JWavePaddle.cpp:135
Text: No moving particles associated with the paddle.


Finished execution (code=1).

**Comment by julesangebault** [comment]
Hi, I have a similar issue and I don't know how to fix it. 

 <DUALSPHYSICS4> Copyright (c) 2019 by
 Dr Jose M. Dominguez, Dr Alejandro Crespo,
 Prof. Moncho Gomez Gesteira,  Prof. Benedict Rogers,
 Dr Georgios Fourtakas, Prof. Peter Stansby, Dr Ricardo Canelas,
 Dr Renato Vacondio, Dr Corrado Altomare, Dr Angelo Tafuni,
 Orlando Garcia-Feal, Dr Jose Gonzalez Cao

 EPHYSLAB Environmental Physics Laboratory, Universidade de Vigo
 School of Mechanical, Aerospace and Civil Engineering, University of Manchester

 DualSPHysics is free software: you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public License
 as published by the Free Software Foundation, either version 2.1 of
 the License, or (at your option) any later version.

 DualSPHysics is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with DualSPHysics. If not, see <http://www.gnu.org/licenses/>.


DualSPHysics4 [Symmetry] v4.4.053 (19-01-2020)
===============================================
LoadDsphConfig> .../bin/windows/DsphConfig.xml
[Select CUDA Device]
[CUDA Capable device(s)]
  Detected 1 CUDA Capable device(s)
  CUDA Driver Version / Runtime Version: 10.2 / 9.2
 
Device 0: "GeForce MX150"
  CUDA Capability Major....: 6.1
  Global memory............: 2048 MBytes
  CUDA Cores...............: 384 ( 3 Multiprocessors, 128 CUDA Cores/MP)
  GPU Max Clock rate.......: 1532 MHz (1.53 GHz)
  Memory Clock rate........: 3004 Mhz
  Memory Bus Width.........: 64-bit
  L2 Cache Size............: 512 KBytes
  Constant memory..........: 64 KBytes
  Shared memory per block..: 48 KBytes
  Registers per block......: 65536
  Maximum threads per MP...: 2048
  Maximum threads per block: 1024
  Concurrent copy and kernel execution....: Yes with 5 copy engine(s)
  Run time limit on kernels...............: No
  Integrated GPU sharing Host Memory......: No
  Support host page-locked memory mapping.: Yes
  Device has ECC support..................: Disabled
  CUDA Device Driver Mode (TCC or WDDM)...: WDDM (Windows Display Driver Model)
  Device supports Unified Addressing (UVA): Yes
  Device PCI (Domain / Bus / location)....: 0 / 1 / 0
  Device supports P2P and RDMA............: No
 
[GPU Hardware]
Device default: 0  "GeForce MX150"
Compute capability: 6.1
Memory global: 2048 MB
Memory shared: 49152 Bytes

[Initialising JSphGpuSingle  29-05-2020 01:01:59]
ProgramFile=".../bin/windows/DualSPHysics4.4_win64.exe"
ExecutionDir=".../FreeCAD/Mod/DesignSPHysics"
XmlFile=".../S3/S3_out/S3.xml"
OutputDir=".../S3/S3/S3_out"
OutputDataDir=".../S3/S3/S3_out"
**Basic case configuration is loaded
**Special case configuration is loaded
Loading initial state of particles...
Loaded particles: 218628
MapRealPos(border)=(-0.075,-0.0155885,-0.0155885)-(49.875,9.76559,2.56559)
MapRealPos(final)=(-0.075,-0.0155885,-0.0155885)-(49.875,9.76559,2.56559)
**Initial state of particles is loaded
**3D-Simulation parameters:
CaseName="S3"
RunName="S3"
Symmetry=False
SavePosDouble=False
SvTimers=True
Boundary="DBC"
StepAlgorithm="Symplectic"
Kernel="Wendland"
Viscosity="Artificial"
  Visco=0.020000
  ViscoBoundFactor=0.000000
DensityDiffusion="None"
Shifting="None"
RigidAlgorithm="None"
FloatingCount=0
CaseNp=218628
CaseNbound=24671
CaseNfixed=21978
CaseNmoving=2693
CaseNfloat=0
CaseNfluid=193957
PeriodicActive="Axis-X"
PeriodicXinc=(-49.95,0,0)
Dx=0.15
H=0.311769
CoefficientH=1.2
CteB=514285.718750
Gamma=7.000000
RhopZero=1000.000000
Cs0=60
CFLnumber=0.200000
DtIni=0.00519615
DtMin=0.000259808
DtAllParticles=False
MassFluid=3.375000
MassBound=3.375000
Awen (Wendland)=13.786315
Bwen (Wendland)=-221.099182
TimeMax=3
TimePart=0.025
Gravity=(0.000000,0.000000,-9.810000)
NpMinimum=24671
RhopOut=True
RhopOutMin=700.000000
RhopOutMax=1300.000000
WrnPartsOut=True
**Requested GPU memory for 218638 particles: 35.0 MB (0 times).
CellMode="2H"
Hdiv=1
MapCells=(83,16,5)
DomCells=(83,16,5)
DomCellCode="14_11_8"
PosCellCode="13_10_9 (8192,1024,512)"
 
BlockSize calculation mode: Fixed.
  BsForcesBound=128 (42 regs)
  BsForcesFluid=128 (52 regs)
 
**JSphGpu: Requesting gpu memory for 230136 particles: 36.9 MB.
**CellDiv: Requested gpu memory for 234428 particles: 1.8 MB.
**CellDiv: Requested gpu memory for 7055 cells (CellMode=2H): 0.1 MB.
 
RunMode="Pos-Cell - Single-Gpu"
 
Particle summary:
  Fixed....: 21978  id:(0-21977)   MKs:1 (10)
  Moving...: 2693  id:(21978-24670)   MKs:1 (11)
  Floating.: 0
  Fluid....: 193957  id:(24671-218627)   MKs:1 (2)

Total particles: 218628 (bound=24671 (fx=21978 mv=2693 ft=0) fluid=193957)
Total MK blocks: 3 (bound=2 (fx=1 mv=1 ft=0) fluid=1)
 
Wave paddles configuration:

*** Exception (JWavePaddleRegular::CheckConfig)
Text: Paddle without range of motion particles valid.


Finished execution (code=1).
