### ISSUE TITLE
GenCase not being executed

### ISSUE THREAD

**Issue by bladomas** [DualSPHysics/DesignSPHysics#3]
![image](https://user-images.githubusercontent.com/30475290/46349067-48278400-c651-11e8-8c67-4ebce57fc6ca.png)

I have manually installed DesignSPHysics. When I execute the macro, the correct side panel pops up. I loaded up the first example for DualSPHysics and made it properly 2D. The first issue that arises is the fact that Box4 is not shown in the load order although I have added it to the DSPH simulation (I get the Object properties windows). If I remove both boxes and add first box4, then box2 does not show up. I do not understand why both do not appear. 
The next issue arises when I try to save case and run GenCase. It does not get run (In case summary says it wasn't run). When I check the Setup Plugin box and click Ok, it says the path of the executables is not correct, I say ok (load the defaults). Open the Setup Plugin box again, same paths are shown and gives the same error. If I manually path to them, gives either the error, not an executable or wrong path. Once I gave execution permissions (chmod +x whole bin folder) it finds all executables by default except DualSPHysics path, if I add it manually from the bin folder it still gives the same error as before. Even after adding GenCase properly (so far I know), the script is not run when I press " save case and run GenCase". 

I know this is a lot, but I'm not sure what I can do to continue. I was simply trying to practise with using DesignSPHysics.

I have attached an image trying to show what I am talking about.  

Edit: GenCase somehow cannot read the .xml file that is created. When comparing to the example files, there are minimal differences but mostly the files are the same. Will try to manipulate them.

**Comment by LoreDocasar** [comment]
Which version are you using?
I recommend you try the release version, please tell me if you are using this version or a version from the repository.

**Comment by bladomas** [comment]
Version of FreeCAD? Version 0.16 I believe, and it is from the repository.

**Comment by LoreDocasar** [comment]
I'm sorry if I explained myself wrong. I mean the version of DesignSPHysics, is the release version or a clone from github?

**Comment by bladomas** [comment]
It is from Github, if I get the release version from a different website it does not work (I cannot run the installer, it gives errors)

**Comment by LoreDocasar** [comment]
The problen that you describe is solved in the release version an in the develop branch.
Please, try to install manually a release version, you can read the guide here -> https://github.com/DualSPHysics/DesignSPHysics/wiki/Installation

See the "Manually Install" section and try again please.

**Comment by bladomas** [comment]
I have manually installed the current version I am using, but tomorrow I will try to install the version you linked.

**Comment by bladomas** [comment]
It works now, so far I know. I can execute GenCase, and the other functions work as well. Much appreciated for the help.

**Comment by bladomas** [comment]
If I follow that exact order, it seems to work (The windows shows calculating and has 0% progress so far). This is weird, perhaps when I repeat the GenCase twice, or if I load a case, or some other action it does not work anymore. If I am able to reproduce and narrow down what causes the bug, I will let you know. Once again, thank you.

**Comment by LoreDocasar** [comment]
For the moment we close the issue, Thanks for reporting!
