### ISSUE TITLE
Acceleration Inputs in Special in DesignSPHysics-master cannot be used

### ISSUE THREAD

**Issue by WangJJ666** [DualSPHysics/DesignSPHysics#31]
When I use the DesignSPHysics-master version, I encounter the situation where the Acceleration Inputs in the special cannot be used, an error is reported: list index out of range. Has anyone encountered such a problem?

**Comment by zlotny** [comment]
I don't know why you closed the issue but indeed in the master branch that was broken. It is fixed now.

I assume you switched to develop and solved the problem for you but that doesn't mean it was fixed :)
