### ISSUE TITLE
Error when setting the irregular motion of piston

### ISSUE THREAD

**Issue by WangJJ666** [DualSPHysics/DesignSPHysics#32]
I think you should have made changes in the develop version. I downloaded the latest version, deleted the previous one, and set the new one, but the same problem still occurs. The error text on the error window is:

[Initialising JSphGpuSingle  11-12-2019 16:54:00]
ProgramFile=".../dualsphysics/bin/DualSPHysics4.4_win64.exe"
ExecutionDir=".../FreeCAD/Mod/DesignSPHysics-master"
XmlFile=".../1205-WAVEPISTON-ASWS-test/1205-WAVEPISTON-ASWS-test_out/1205-WAVEPISTON-ASWS-test.xml"
OutputDir=".../DualSPHysicsProjects/1205-WAVEPISTON-ASWS-test/1205-WAVEPISTON-ASWS-test_out"
OutputDataDir=".../DualSPHysicsProjects/1205-WAVEPISTON-ASWS-test/1205-WAVEPISTON-ASWS-test_out"

*** Exception (JXml::ErrReadElement)
Text: Error reading xml - Element 'spectrum' is invalid.
File: E:/DualSPHysicsProjects/1205-WAVEPISTON-ASWS-test/1205-WAVEPISTON-ASWS-test_out/1205-WAVEPISTON-ASWS-test.xml(row:86)

Finished execution (code=1).

**Comment by zlotny** [comment]
Hi there! Thanks for the issue. In fact this was detected yesterday and was fixed in commit ab92c0655317cd196c99150698ab4a9142c5a428 already, on the develop branch.

I'll update the master branch so everyone can update the software and have this fixed :)

**Comment by zlotny** [comment]
It is ready now for you to update. Sorry about that. Thanks for your help!

**Comment by WangJJ666** [comment]
*** Exception (JXml::ErrReadElement)
Text: Error reading xml - Element 'spectrum' is invalid.
File: E:/DualSPHysicsProjects/1205-WAVEPISTON-ASWS-test/1205-WAVEPISTON-ASWS-test_out/1205-WAVEPISTON-ASWS-test.xml(row:81)


Finished execution (code=1).
