### ISSUE TITLE
Error when setting the irregular motion of piston 

### ISSUE THREAD

**Issue by WangJJ666** [DualSPHysics/DesignSPHysics#33]
Sorry, I just downloaded the latest version of master branch.
![image](https://user-images.githubusercontent.com/58459423/70622383-c8367a00-1c56-11ea-988b-e42b345d8108.png)
I tried many times, but the irregular  function is still not working. The error window still says:
*** Exception (JXml::ErrReadElement)
Text: Error reading xml - Element 'spectrum' is invalid.
File: E:/DualSPHysicsProjects/1205-WAVEPISTON-ASWS-test/1205-WAVEPISTON-ASWS-test_out/1205-WAVEPISTON-ASWS-test.xml(row:81)

Finished execution (code=1).
Please check it again.

**Comment by zlotny** [comment]
That should be impossible assuming you did follow the instructions I gave you in https://github.com/DualSPHysics/DesignSPHysics/issues/30#issuecomment-563932366

The code now writes into the case (and thus, into disk) a correct spectrum definition but you need to delete the movement and create it again for DesignSPHysics to write the correct values.

As I said, please do what I explained on this comment: https://github.com/DualSPHysics/DesignSPHysics/issues/30#issuecomment-563932366

And try again. If that does not work please attach the 1205-WAVEPISTON-ASWS-test.xml file to see what the tag <spectrum> contains.

**Comment by zlotny** [comment]
Nevermind, indeed there was a problem while generating the Irregular Flap and Piston objects on memory, in which DesignSPHysics would save a number (0, 1...) instead of the according enumerated value that contain the correct text (jonswap, pierson...)

The issue should now be fixed now on the master branch so you can update.
