### ISSUE TITLE
Moorings in Special in DesignSPHysics-master cannot be used

### ISSUE THREAD

**Issue by moroth89** [DualSPHysics/DesignSPHysics#38]
Hello everyone, 

as soon as I assign floating to a body, it is no longer possible to select "Moorings" in the Special section. 
Do I have to activate a certain setting to define the mooring lines or is the function not yet fully available? 

Many thanks in advance!

Kind regards 
Moritz
[LC_201_mooring_Def.txt](https://github.com/DualSPHysics/DesignSPHysics/files/4029430/LC_201_mooring_Def.txt)
![_2020-01-07_14-27-30](https://user-images.githubusercontent.com/59596749/71876726-0c377480-315a-11ea-81ca-8a030aedef99.jpg)

**Comment by zlotny** [comment]
Indeed it was an error on the code. It was already solved on the develop branch.

I updated the master branch so you can update. Please use the addon manager to update your DesignSPHysics version and it should be solved.

Sorry for the inconvenience and thanks for reporting the issue!

**Comment by moroth89** [comment]
Thanks a lot for your help. Now it's working!
