### ISSUE TITLE
Only one object being created / other objects not shown in object order

### ISSUE THREAD

**Issue by badbunny-uk** [DualSPHysics/DesignSPHysics#4]
Hi, I am trying to follow the dam breaking tutorial on [http://design.sphysics.org/wiki/doku.php?id=tutorials](url) but am unable to complete the simulation.

I have a problem that when I use the 'Add to DSPH simulation' button, objects are not appearing in the 'object order' dialog, and are thus not being written out with the simulation files. For example if I click on each oject in turn and click on the 'Add to DSPH simulation' button (for all of them individually) only the first one is added to the 'object order' dialog. Looking at the xml file I can see that only that one object has been output.

If I then 'Remove from DSPH simulation' that first object, the other five objects suddenly appear in the object order dialog. Even by adding and removing multiple times I can't get all of the objects to be listed in the object order dialog. So there appears to be a problem with the object order dialog not staying up to date with the objects that have been added to the DSPH simulation.

Note - I am running DesignSPHysics 0.5-1807-31 installed using the Freecad 0.18 addon manager (on Windows 10 64bit - I've also replicated the problem on another machine running Windows 7 64bit).

Thanks,
Pete.

**Comment by LoreDocasar** [comment]
Can you try again with the new version 0.5.1811-08?

You can download it from the following link:
    https://github.com/DualSPHysics/DesignSPHysics

In this new version some bugs was solved.

**Comment by badbunny-uk** [comment]
Hi, I tried your suggestion and that version works for me.

Thanks,
Peter,
