### ISSUE TITLE
Use of Chrono + Mooring 

### ISSUE THREAD

**Issue by moroth89** [DualSPHysics/DesignSPHysics#45]
Hello, 

When I try to start the simulation, an error message occurs after initialization. 

*** Exception (JChLinkHinge::AddBodyRef) at .../DSPHChronoLib/Source/JChronoData.cpp:592
Text: Number of requested reference is invalid.

In my case I connected several floats with the link hinge function and anchored them with four mooring lines. 

I have attached the out file of GenCase. Also the Run.out file. 

If needed I can provide the XML file. 

Thanks a lot in advance. 

Kind regards 
Moritz

[GenCase_out.txt](https://github.com/DualSPHysics/DesignSPHysics/files/4080840/GenCase_out.txt)
[Run_out.txt](https://github.com/DualSPHysics/DesignSPHysics/files/4080841/Run_out.txt)

**Comment by zlotny** [comment]
Hi there. I can't really see how this issue falls in a possible issue with DesignSPHysics, the GUI for DualSPHysics. Maybe you meant to open this issue in https://github.com/DualSPHysics/DualSPHysics ?

**Comment by moroth89** [comment]
Okay, thank you for your quick reply. I will close it.
