### ISSUE TITLE
Suggestions Tutorial

### ISSUE THREAD

**Issue by Tiiri** [DualSPHysics/DesignSPHysics#5]
Hello,
I'm new to DesignSPHysics and started with [this tutorial](http://design.sphysics.org/wiki/doku.php?id=dam-break-example). It worked nicely in the end (at least I guess it's right) and I really enjoy it.
I have some suggestions to make following the tutorial easier.

1.  Why is the renaming only mentioned in Step 4? It could be useful in Step 3 already. (Knowing a little bit about FreeCAD it absolutely clear, but for new people it's a nice hint.)
2. In Step 4 it isn't mentioned to add the cube to the DSPH Simulation. (Not hard to come up with that by myself, but just nice not to skip that.)
3. In the Final Step it is not enough to just press "Save Case" but I have to choose "Save Case and Run GenCase" from the dropdown. Knowing that is very important and not clear!
4. Also in the Final Step the button is not named "Export data to VTK" but "PartVTK". Just confusing. (One question to that point is somewhere an explanation what the different buttons are exporting?)
5. Maybe one screenshot of the results in ParaView would be nice in the end to compare the simulation.

In general maybe somewhere a note that the message `One or more of the executables in the setup is not correct. A DualSPHysics package was detected on your installation. Do you want to load the default configuration?` is nothing to worry about (at least it seems to me like that). I tried quite long to get rid of it by re-installing in different manners.

Thanks for the work! 
I'll definitely spend more time with it.

**Comment by LoreDocasar** [comment]
You are right that this tutorial is obsolete, in fact it is no longer available for the new versions of DesignSPHysics, we are working on new tutorials.
Thanks for your comment! We will consider it.
Greetings.
