### ISSUE TITLE
enhancement? Initial translation and rotation

### ISSUE THREAD

**Issue by EEJGH** [DualSPHysics/DesignSPHysics#52]
Helo, good afternoon,

I know there is a SPHysics feature meant to move around (traslation and rotation) solids after being sampled with particles.

Something like this:

![image](https://user-images.githubusercontent.com/60138925/73746412-6a557880-4755-11ea-86f5-3af4b4afc61b.png)

But I cannot find this in the DesignSPHYsics GUI. I guess it should be accesible clicking on "Initials" for a certain bound (i.e. not a fluid) object, but that button is never available for me...

Maybe I have another problem somewhere else...

The actual problem I want to solve is a coarse definition of what should be a ramp but which due to the cartesian placement of particles gets  sampled as a "staircase". Hence I wanted to redefine the CAD object aligning the "ramp" surface with one of the axis, and then apply the rotation operation as described on the XML Guide for Dual SPHYsics 4.4...

Can anybody please assist? In the meantime I will jsut gennerate the xml and then manually edit it adding the corresponding node...

thanks!

**Comment by zlotny** [comment]
Hi there. Indeed this feature is not present on the GUI. Take in mind DesignSPHysics has a just bare minimum of features to keep people going as a tutorial + as a case bootstrapper, to make a case and then continue with the CLI tool.

However I aim to put all the possible features on the GUI at some point but right now I'm busy in other things.

For now I have to say that you should continue your case via XML edition if you want to use these features.

**Comment by EEJGH** [comment]
Understood, thanks!

**Comment by zlotny** [comment]
Not the specific issue that was discussed here but I reintroduced a missing feature lost in a big refactor that let you choose 3 types of velocities in the initials configuration. Commit 2eac1cdaee0c28698ddb6538401ace0eadab73c9 in develop right now.
