### ISSUE TITLE
Object´s mass definition not working (only floating object´s density works)

### ISSUE THREAD

**Issue by EEJGH** [DualSPHysics/DesignSPHysics#54]
Design SPHysics version 0.6.0.2001-20-4

I ran a very simple simulation with a floating body and a density of 900 kg/m^3. It had a volume of 1 l, so I changed the definition to mass, assigned 0.9 kg, and the GenCase failed reporting

*** Exception (JSpaceFloatingBody::ReadXml)
Text: One value must be defined (massbody, relativeweight or rhopbody).
File: E:/Simulaciones/SPH/Sinking_square/centre_CoG/square_centre/square_centre_Def.xml(row:57)

Any ideas?

Thanks

**Comment by zlotny** [comment]
Indeed that's an error.

For some reason massbody is defined in a tag inside the floating tag while rhopbody is defined as an attribute to the floating tag.

I'll fix it right away, thanks!

**Comment by zlotny** [comment]
That was fixed on commit 2064faa6063f112e9d8a8098c1158a585ee5f594 on the develop branch.

I'll release that and a few more changes on master in a few days.

Thanks!
