### ISSUE TITLE
How to get the wave run up value when the wave reaches the bank? 

### ISSUE THREAD

**Issue by wangjinge1985** [DualSPHysics/DesignSPHysics#55]
Hi, is there anyone knows how to get the wave run up value when the wave reaches the bank? I mean the highest water elevation when the wave hit the solid bank, and also the run up values over time. I have tried to plot the Z value of the particle that very close to the bank over time in ParaView, but the selected particle ID changed randomly during the time, it cannot give a continue curve. Thanks！

**Comment by zlotny** [comment]
Hi there. That question does not seem related to the development of DesignSPHyisics ; More like a question about DualSPHyiscs.

Please ask those kind of questions on the DualSPHysics forum (forums.dual.sphysics.org) as this place is intended for bug reporting and suggestions about the development/programming of the User Interface, DesignSPHysics.
