### ISSUE TITLE
"Actual" vtk outputs for fixed and floating bounds

### ISSUE THREAD

**Issue by EEJGH** [DualSPHysics/DesignSPHysics#56]
Hello,

I hope this the proper place to ask this...

Is htere any way to configure the postprocess so that the "actual" floating bound object files are created in a vtk group? and independently a fixed actual with the fixed bounds?

I ask because I see in the outputs a single vtk "actual" file, which when imported in ParaView clearly displays the initial position of the floating bound + the fixed bound, but I cannot find how ot gennerate the vtk group of "actual" flaoting bounds and separately a fixed actual bound file (which obviously does not require a group)

I hope it is clear what I mean...
thanks!

**Comment by zlotny** [comment]
Hi there. I think that question is more suitable on the forums (forums.dual.sphysics.org) or even in the DualSPHysics repo issues (https://github.com/DualSPHysics/DualSPHysics/issues)

I don't know if what you mean is possible. If I understand correctly what you want is like every Part*.vtk file being constructed like the *Actual.vtk one. Not on particles, but in mesh. Is that right?

It may be possible to do with PartVTK but, if possible, I have no idea on how to do it, as I don't use the DualSPHysics suite a lot myself.

As there was no interaction with other users on the past, and for my experience the people that reach this issue page are absolute beginners with DualSPHyiscs, I believe it is not the best place to ask hehe.

I'll close the issue as the answer to this is: "There's no such option on the GUI, and I don't know if there is an option for that on the CLI. However I'll ask the DualSPHysics developer myself when I see him."
