### ISSUE TITLE
Wrong set up of meassurements leads to crash

### ISSUE THREAD

**Issue by EEJGH** [DualSPHysics/DesignSPHysics#57]
If the user wrongly sets up a meassurement with no point / grid of points information, an error pop up window appears and after cacneliing all the error reports the user gains back control but the process is locked, buttons greyed out, and the only possibility remaining is to close FreeCad and load the case again.

**Comment by zlotny** [comment]
Fixed! thanks for your feedback, it is greatly appreciated :)
