### ISSUE TITLE
error with stl file

### ISSUE THREAD

**Issue by remy-l** [DualSPHysics/DesignSPHysics#58]
Hello, sorry for re opening another issue.

I did all what you told me to do : i reinstalled dualsphysics'macro and installed the most recent one but there is still an error : error executing gencase.
I think it comes from adding an stl file as the simulation works with no stl file.

Thank you again.

note : my stl file was converted from solidworks and was imported on freecad as geo as long as there is no "import stl" button

**Comment by zlotny** [comment]
Sadly I can't do anything about this with this information.

Can you attach your case zipped? Can you paste the GenCase error (there's a ton of info if you click show details)? What DesignSPHysics version are you running?

There's quite a bit of missing information on here. Don't be sorry for opening issues, you're contributing to the project and potentially finding a bug. However, this issue is like leaving a car in a workshop just saying "It doesn't let me go to my job in the mornings". I need more information about what is wrong.

**Comment by remy-l** [comment]
Sorry, i give you mre details : 
Here is my case : 
[casedata.zip](https://github.com/DualSPHysics/DesignSPHysics/files/4203807/casedata.zip)

Here is my stl file : 
[surfboard.zip](https://github.com/DualSPHysics/DesignSPHysics/files/4203810/surfboard.zip)

And finally here is the error : 
"error executing gencase : did you add object to the case ? Another reason could be memory issue."
more details : 

"

 <GENCASE4>  Copyright (c) 2019 by Dr Jose M. Dominguez
 All rights reserved.

 DualSPHysics is an international collaboration between University of Vigo 
 (Spain) and University of Manchester (UK). 

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions
 are met:
 * Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
 * Neither the name of the DualSPHysics nor the names of its contributors
   may be used to endorse or promote products derived from this software
   without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER BE LIABLE FOR ANY
 DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 


GenCase4 v4.0.140 (07-01-2020) 
================================
LoadDsphConfig> .../dualsphysics/bin/DsphConfig.xml
OmpThreads: 4

[LoadXML]

*** Exception (JSpaceFloatingBody::ReadXml) at ..\Source\JSpaceFloating.cpp:134
Text: One value must be defined (massbody, relativeweight or rhopbody).
File: D:/cours/TIPE/casewavefloating/casewavefloating_Def.xml(row:72)


Finished execution (code=1).

"
I have configured the massbody to 75.0 kg with MKbound 3

Thank you

**Comment by zlotny** [comment]
Thanks for the details. It was indeed a bug, submitted in the issue #54 

It was already fixed but not published yet on the branch master. I've merged the changes from develop onto master so you can update and solve the issue.

So please update your DesignSPHysics installation (just yo to the addon manager and click Install/Update) and try again.

**Comment by remy-l** [comment]
After updating DesignSPHysics, the simulation indeed works, but has apparently forgotten the stl file : everything appends well : run gencase is ok, open in paraview is ok, but when I check the paraview file, my stl surfboard has disappeared : 

[paraview bug.zip](https://github.com/DualSPHysics/DesignSPHysics/files/4204034/paraview.bug.zip)

I've not modified my case : 
[case2.zip](https://github.com/DualSPHysics/DesignSPHysics/files/4204044/case2.zip)

**Comment by zlotny** [comment]
Hi there. Your surfboard is outside the 2D case limits/slice :)

![image](https://user-images.githubusercontent.com/6155245/74524394-3c272400-4f1f-11ea-8cd9-fdcab7a16511.png)

Just move it a bit to +Y:

![image](https://user-images.githubusercontent.com/6155245/74524439-53661180-4f1f-11ea-92c1-5e5f7d1cb033.png)


And it will be fine:
![image](https://user-images.githubusercontent.com/6155245/74524480-6678e180-4f1f-11ea-8acd-df1079a7738c.png)


Hope that helps.

**Comment by remy-l** [comment]
ahahaha i'm a fool.

The simulation is processing, thank you very much !

Have a nice day :)

**Comment by zlotny** [comment]
Don't worry, everything is difficult when you begin learning it :)

Thank you for contributing to the project. Closing this issue now as it seems resolved!
