### ISSUE TITLE
type object 'PySide2.QtCore.QTextCodec' has no attribute 'setCodecForCStrings'

### ISSUE THREAD

**Issue by UndeadJaeger** [DualSPHysics/DesignSPHysics#6]
The line QtCore.QTextCodec.setCodecForCStrings(QtCore.QTextCodec.codecForName('UTF-8')) in DesignSPHysics.py cannot be executed when using Qt5 returning the following error. This is caused by the fact that setCodecForCStrings is not supported anymore in Qt5. This causes the macro to fail.

Problem can be solved for now by commenting out this line.

Problem occurred using Ubuntu 18.04.1.

**Comment by LoreDocasar** [comment]
Does the error occur when you use the installer?

If so, try to install it manually.
https://github.com/DualSPHysics/DesignSPHysics/wiki/Installation


I will review it, thanks for your comment!

**Comment by UndeadJaeger** [comment]
I've used the version from the repository.

**Comment by LoreDocasar** [comment]
But how did you install it? With the installer or manually?

**Comment by UndeadJaeger** [comment]
Ah, my apologies. I installed it manually, so renaming the folder, copying to the Mod folder and copying of the FCMacro file to the Macro folder.

Commenting out the line solves the running of the macro and shows the DesignSPHysics interface. Only functionality is limited (I cannot add object to the simulation). I don't know if that is related.

I was thinking to just revert to an older LTS release of Ubuntu for now.

**Comment by GCE-Galotta** [comment]
Any news on this?

**Comment by LoreDocasar** [comment]
At this moment tests are being carried out and the error will be corrected as soon as possible.

Thanks for your comments!

**Comment by LoreDocasar** [comment]
The new version of the macro is ready.
This new version is already compatible with FreeCAD 0.18, so it does NOT work with FreeCAD 0.17

You can download it from the official page:

https://design.sphysics.org/

Or from github:

https://github.com/DualSPHysics/DesignSPHysics

Thanks for your comments!
