### ISSUE TITLE
Special Mooring no longer available

### ISSUE THREAD

**Issue by moroth89** [DualSPHysics/DesignSPHysics#63]
Hello, 
I downloaded the latest version of Designphysics today and it is no longer possible to implement mooring lines. 
![DesignPhysiscs](https://user-images.githubusercontent.com/59596749/78011146-8172aa00-7343-11ea-8552-1c0e29200a29.PNG)

Is it possible to reintegrate the option? 

Best regards 
Moritz

**Comment by zlotny** [comment]
Hi there. From commit f529ed50da1a7c508202090428aac2c41ac31981 and onwards the GUI only shows the options that are available on the DualSPHysics executable.

The latest binaries don't include Moorings and Fourtakas DDT, so they're hidden from the interface.

To use moorings you have 2 options:

* First one is to provide to DesignSPHysics a DualSPHysics executable that supports moorings, which you could have if you went to any recent DualSPHysics course / training session. I cannot provide the executables myself as I'm told not to release them (the fact that they were here was a communication problem :) now they're removed, sorry about that) but you can always ask on the forums (forums.dual.sphysics.org) how to get them.

* Second one is to just force the option to appear. In Setup Plugin you'll notice there's a second tab in which you can force MoorDyn support so the option shows up and saves on the XML. However it would not run correctly without executables that support the feature. (Screenshot below on where the option is).

![image](https://user-images.githubusercontent.com/6155245/78118305-1d191e80-7407-11ea-8044-535ed668c188.png)


Sorry about removing the executables that were available here in the app a while ago, as they shouldn't be released (they were on development state and definitely not stable or correct in many ways). I hope this solves or lightens something so you can continue working.

Thanks for using DesignSPHysics :) Closing now, as it is *solved*

**Comment by moroth89** [comment]
Many thanks for the quick answer. I was surprised, because I have reproduced the case from the paper "SPH simulation of floating structures with moorings" by Dominguez et al. with the version 0.6.0.2001-30-2. Thereby I got different results in the post-processing. 

I will try my luck in the DualSPHysics Forum. 

Best regards
Moritz

**Comment by zlotny** [comment]
Take in mind the version of DesignSPHysics (the GUI) is not directly linked with which executables are used in the backend, which you can specify on the "Setup Plugin" window.

Probably Jose (Domínguez) and Alex (et al... :)) were using their own development compiled executables to design and execute the cases.
