### ISSUE TITLE
I would like to include you in the acknowledgment of my paper

### ISSUE THREAD

**Issue by WangJJ666** [DualSPHysics/DesignSPHysics#64]
Thank you for answering my questions before. I would like to include you in the acknowledgment of my paper. I'm wondering if it is OK to tell me your name?

**Comment by zlotny** [comment]
Of course, it is public in a few files around this repository, including the contribution rules file :)

My name is Andrés Vieira Vázquez and the project is being developed on EPhysLab (Environmental Physics Laboratory) in the Universidade de Vigo  (University of Vigo)

Thank you so much for wanting to have me included!
