### ISSUE TITLE
Trouble Running Case with GPU

### ISSUE THREAD

**Issue by Sal-AL** [DualSPHysics/DesignSPHysics#65]
Hi 

I am currently having trouble running the case with my GPU. I get the following error message. I am using a dedicated 4gb graphics card so this should work. Think it is having trouble finding it??
Thank you for any help!

DualSPHysics4 [Symmetry] v4.4.053 (19-01-2020)
===============================================
LoadDsphConfig> .../dualsphysics/bin/DsphConfig.xml
[Select CUDA Device]

*** Exception (../source/FunctionsCuda.cpp::GetCudaDevicesInfo:145)
Text: Failed getting devices info. (CUDA error 35 (CUDA driver version is insufficient for CUDA runtime version)).

**Comment by zlotny** [comment]
Hi there. This error seems more related with DualSPHysics that with DesignSPHysics. 

However the error messages states very clearly that your CUDA driver version is insufficient. 

Just update CUDA and run again.

**Comment by Sal-AL** [comment]
Thank you for the quick response!
Ahh i am using an AMD graphics card ...
So i am correcting in saying DualSPHyics will only run on a Nvidia GPU?

**Comment by zlotny** [comment]
Oh. Yes of course. DualSPHyiscs on GPU runs on CUDA, which is proprietary and specific to nvidia. You can't run GPU simulations with AMD cards :(

There was some work/insight a while ago on porting DualSPHyiscs to other GPU platforms but as the science market is basically mostly nvidia it was discarded as it is a lot of work to port it.

However if you want to ask more information about that please do so on https://github.com/DualSPHysics/DualSPHysics which is the solver itself, this is only a GUI.

Closing this now as it is kind of solved.

**Comment by Sal-AL** [comment]
Okay cheers for the help anyway man
