### ISSUE TITLE
Motion Button Greyed out - Can't edit motion

### ISSUE THREAD

**Issue by Sal-AL** [DualSPHysics/DesignSPHysics#66]
Hello

Does anyone know why the motion button is greyed out. Doesn't let us edit the motion for some reason ... sometimes it starts working but then stops.

Thank you for your help!

![Motion_Issue](https://user-images.githubusercontent.com/63190027/78999174-ff079880-7b41-11ea-834f-1de284295d03.JPG)

**Comment by zlotny** [comment]
I'v been checking this and it seems the Configure button does not refresh for complex objects correctly. If you had a bound selected (with the Configure button enabled) and then you click your "Walls" object (a boolean compound object, treated as "complex" in DesignSPHysics), the button will remain active. However if you have a fluid selected (the button is disabled as fluid can't have movements) and then you click "Walls" the Configure button will be disabled.

I'll try to find a fix for this. Thanks for noticing!

**Comment by zlotny** [comment]
This should be already fixed.

Commits: 5eb3edf0b9b6e963ca7ff616c17900ce5d863aba and 1b96496e7e17ee4ef1fe26fbc8539370b1af2047 change the button behaviour so it gets activated under the right conditions.

**Comment by Sal-AL** [comment]
Okay thank you!
