### ISSUE TITLE
Issue with opening old DSPH case with the latest version

### ISSUE THREAD

**Issue by eleclizard** [DualSPHysics/DesignSPHysics#67]
Hi,

I have a DSPH case file made in version 0.6.0.1912-12-3 and since there is a new version of DSPH addon for DSPH 0.6.0.2004-13-03, I cannot run this old DSPH file now. Should recreate my case using the new version or is there another way that I can work around this issue and convert my old DSPH case to the new version

Thanks

**Comment by zlotny** [comment]
Hi there. Unfortunately as of today you'll need to re-create the case again. DesignSPHysics is close to be "feature complete" (for what the DualSPHyisics team want) so once we get there there will be work on making new versions backwards compatible with old cases.

For now, though, the software expects the same data structure saved to disk as it has on it's internal structure, so as that's changing every now and then, it's usual to find that a case is too old to be loaded. 

Sorry about that.

**Comment by zlotny** [comment]
Closing this as it's not planned to support old files until we reach a *complete* version.
