### ISSUE TITLE
Missing Fluid.vtk file

### ISSUE THREAD

**Issue by MMunir-MY** [DualSPHysics/DesignSPHysics#69]
Hi, I have a problem with my 3d beach model. I used a fillbox to represent the water and set it as fluid. However, when I ran the GenCase, I couldn't open the fluid.vtk in ParaView. When I checked my folder, there is no fluid.vtk file created. 
Do I miss any important step?

[Case_Def.txt](https://github.com/DualSPHysics/DesignSPHysics/files/4484861/Case_Def.txt)

**Comment by zlotny** [comment]
Hi there. This doesn't seem an issue with DesignSPHysics, but with the design of the case. You should post this kinds of doubts on the DualSPHysics forums (forums.dual.sphysics.org). 

For what I can read on the definition you attached the fill point for the fill box is outside the area limits of the fillbox (0,0,0) is not inside (0.5, 0.5, 0.5 to 20.0, 4.0, 0.5) so It wont fill any fluid.

The fill point has to be inside the fillbox and it will fill until boundary is reached or the fill limits are reached.

Closing as is does not seem like an issue/bug/feature request for the GUI.

**Comment by MMunir-MY** [comment]
Oh so thats where i miss look.. Thank you sir!

Sent from Yahoo Mail on Android 
 
  On Thu, 16 Apr 2020 at 17:03, Andrés Vieira<notifications@github.com> wrote:   


Closed #69.
