### ISSUE TITLE
there are some different using designSPHysics and xml（bat）with the same parameters

### ISSUE THREAD

**Issue by junzeng96** [DualSPHysics/DesignSPHysics#7]
hello，thanks for the designsphysics，the GUI is friendly for users. 
but when i test a dambreak case，i found that the pressure and force exist some different compared using xml and bat with same parameters. is that normal？

**Comment by LoreDocasar** [comment]
Hello, 
In the following link you can get more information about your question:

https://dual.sphysics.org/vanilla/discussion/1546/designsphysics-is-different-form-dualsphysics

Thanks for your comment.
