### ISSUE TITLE
Using Dualsphysics with GCP (Google Computing cCoud)

### ISSUE THREAD

**Issue by Sal-AL** [DualSPHysics/DesignSPHysics#73]
Hi 

Recently ran a sim on GCP. Unsure what files I need to run in ParaView to simulate. I took just the fluid vtk and bound vtk but it didn't work. If this is not the correct forum can you please re-direct! Thank you!

**Comment by zlotny** [comment]
Hi there. This is not a forum, but an issue tracker for issues, bugs and improvements on the source code of DesignSPHysics, the GUI for DualSPHysics.

About your issue, you're using DualSPHysics only, it seems, to this suites better the actual forums: forums.dual.sphysics.org.

To try and answer your question I suppose you want to see the time steps of your simulation with Paraview. For that you'll need the parts exported by PartVTK (usually named Part*01.vtk and so on) and open them all in paraview.

I'm closing the issue as it's not a solvable problem on the code of DesignSPHysics, but a question related to DualSPHysics.

Please ask on the forums if you have further questions about usage, doubts or need guidance.

**Comment by Sal-AL** [comment]
Thank you for your help! Going forward i'll be sure to use the correct forum
