### ISSUE TITLE
Report error

### ISSUE THREAD

**Issue by Salehmeiabadi** [DualSPHysics/DesignSPHysics#74]
I just installed FreeCAD, and added DesignSPHysics, started the floating body case and tried to run Gencase/ParaView and received this error:
DesignSPHysics version: 0.6.0.2004-16-02
Platform: Windows-8-6.2.9200-SP0
FreeCAD Version: 0.18.4 (GitTag)
Exception type: <class 'UnicodeDecodeError'>
Exception value: 'utf-8' codec can't decode byte 0xc9 in position 3441: invalid continuation byte
Traceback:
  File"C:\Users\saleh\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\widgets\dock\dock_pre_processing_widget.py", line 230, in on_execute_gencase
    output = str(process.readAllStandardOutput().data(), encoding='utf-8')
Please let me what is the problem

**Comment by zlotny** [comment]
Hi there!

This is caused by DesignSPHysics not being able to decode the output of GenCase. However this is an strange issue and I'll have to have a look at it more closely to get what's going on.

I'm assuming the language on your Windows machine is one with non UTF-8 characters, maybe arab?

Can you please tell me the language of your Windows so I try to replicate this and fix it?

If you have access to an english (or whatever other language with english-like characters) computer please try using DesignSPHysics on that in the meantime as this bug can take me a while to replicate and fix.

Sorry about the inconvenience.

**Comment by Salehmeiabadi** [comment]
Hi
Thank you for your response.
I have both EN and Persian languages.
I do not this is helpful or not; when I just run the simulation I got the following:
![1](https://user-images.githubusercontent.com/64735834/80924174-7b625580-8d55-11ea-8f7c-cf6e69787a12.jpg)
When I click on RunGencase I face the above problem.
Thanks

**Comment by zlotny** [comment]
Oh I see. Persian uses the Windows-1256 encoding under Microsoft Windows, which is not compatible with UTF-8, which most applications work with.

However it seems that GenCase executed correctly at least so you could go on and simulate. Did you change something or it just worked and let you continue with simulating?

About the warnings, those are find. Those are not errors but DualSPHysics simulation warnings. You can show them by clicking in show warnings and usually are DualSPHysics usage related stuff. 

I'll try to fix the encoding issue, but for that I have to find a way to install Windows in persian to test the problem :)

**Comment by Salehmeiabadi** [comment]
Thanks for your prompt response.
I did not change anything.
When I click on Run (in the Simulation control) I get this warning:
![1](https://user-images.githubusercontent.com/64735834/80925477-0d6e5c00-8d5e-11ea-8b04-28a4d84f5806.jpg)
If I click Ok the simulation starts.
..
When I click on Run GenCase, the following appears 
![2](https://user-images.githubusercontent.com/64735834/80925555-b2893480-8d5e-11ea-9722-eaa04ee26eb4.jpg)
..
Isn't it related to ParaView?
Because when I installed DesignSPHysics, I tried to set up plugin, however, there was no ParaView folder in my program file on my PC.
And I installed only ParaView again and set up plugin for ParaView.

**Comment by zlotny** [comment]
I think it's now solved. It appears to be a problem with the character 'ة'. It's possible that you'll see some strange characters in the output, but at least it should work fine.

Let me know if the issue persist once you update DesignSPHysics

**Comment by Salehmeiabadi** [comment]
Thanks for your support.
I started the simulation by click on Run GenCase and the following appeared:
![-1](https://user-images.githubusercontent.com/64735834/80973636-a4cec000-8ded-11ea-908d-2152a06b2f54.png)
and my next step:
![1](https://user-images.githubusercontent.com/64735834/80973794-d8114f00-8ded-11ea-83fa-05dfeaa2ee71.png)
I faced with this error(Not responding)
![1](https://user-images.githubusercontent.com/64735834/80973893-f5deb400-8ded-11ea-880e-877cd203be72.png)
Finally the it could not debug the problem:
![2](https://user-images.githubusercontent.com/64735834/80974033-2cb4ca00-8dee-11ea-8664-07abe225d705.png)
Do you think I need to reinstall Paraview?

**Comment by zlotny** [comment]
I think your problem is that you have *a lot* of particles in your case. You probably don't have so much RAM to hold all of that and Paraview hangs.

Try to do an smaller case and see if it helps. If it hangs anyway maybe there's a problem with that installation of paraview.

**Comment by Salehmeiabadi** [comment]
Dear Zlotny
To reduce the number of particles to avoid problems related to my low CPU, I reduced the volumetric scale of the case to 1:100.
For this time, the number of particles was 20502 and I could run the simulation
![0](https://user-images.githubusercontent.com/64735834/81112342-7edc1500-8eec-11ea-8b09-5742b59fc1c1.jpg)
![1](https://user-images.githubusercontent.com/64735834/81112388-94513f00-8eec-11ea-913f-19ccfe6acdf5.jpg)
 but I could not open the case by ParaView.
![2](https://user-images.githubusercontent.com/64735834/81112403-9a472000-8eec-11ea-8f6f-572dad2fd216.jpg)
I know that DesignSPHysics is your area of interest.
Anyway, do you think there is any solution to this problem?

**Comment by zlotny** [comment]
Oh, look at the errors. The problem seems to be with OpenGL, not memory. I had an email a few days ago stating that paraview 5.6.0 didn't have a problem with OpenGL rendering that 5.8.0 had.

Could you try to use paraview 5.6.0 to see if something changes? I don't know a lot about paraview so maybe that does not solve anything, but it's the only thing I can think of

**Comment by Salehmeiabadi** [comment]
Dear Zlotny
I just wanted to thank you for your help.
And I wanted to share my finding that ParaView 4.4.0 works very well with DesignSPHysics.
Best regards

**Comment by zlotny** [comment]
I'm glad that you found a solution :) Let's consider this solved then!

Thanks for using DesignSPHysics.
