### ISSUE TITLE
Can't installed DesignSphysics 

### ISSUE THREAD

**Issue by julesangebault** [DualSPHysics/DesignSPHysics#75]
Hi, 

I would like to install DesignSphycics on freeCad 0.18 but when I tried to install the addon. It tell me that DesignSphysics is installed but I can't find the Macro to execut it. 

I tried to unistall freeCad and install it again but nothing works... 

![addonmanager](https://user-images.githubusercontent.com/65227384/83008680-d6663000-a015-11ea-80c2-fb3f6ed99300.jpg)
![macro](https://user-images.githubusercontent.com/65227384/83008683-d6fec680-a015-11ea-88f9-3a7528de6815.jpg)

**Comment by zlotny** [comment]
Hi there. I think FreeCAD's addon manager installs workbenches and macros on the folder %appdata%/FreeCAD/Macro directory (In windows 10 that is: C:/Users/{name}/AppData/Roaming/FreeCAD/Macro) but you have set the macros location to C:/Program Files/FreeCAD 0.18/lib.

Try changing that to the former location to see if its there. If not please download it again once the appropriate path is set.

**Comment by julesangebault** [comment]
Hi, I tried to download it again with the appropriate path but still not working.
 A error message appeared saying: GitPython not found. Using standard downloade instead.

**Comment by zlotny** [comment]
That's an error with FreeCAD. I can't do much in there. However it should still download no mather if GitPython is present or not.

If you still can't download the addon, that's definitely an error with FreeCAD, please ask to their developers on the forum (https://forum.freecadweb.org/) or open an issue in their repository for addons + addon manager (https://github.com/FreeCAD/FreeCAD-addons/issues) as this has nothing to do with the code of DesignSPHyiscs.

Anyway in my tests usually when that notice (not error) of GitPython appears it just downloads by other means. It takes a while, though, but that's again a problem with FreeCAD, not this.

**Comment by julesangebault** [comment]
Okay I'll do this. 
Thank you for your answers!
