### ISSUE TITLE
*** Exception (JWavePaddleRegular::CheckConfig) Text: Paddle without range of motion particles valid.

### ISSUE THREAD

**Issue by julesangebault** [DualSPHysics/DesignSPHysics#76]
Hi, 
I'm trying to do a wave generator but I always get the same issue and don't know why... Could you help me please. 

 <DUALSPHYSICS4> Copyright (c) 2019 by
 Dr Jose M. Dominguez, Dr Alejandro Crespo,
 Prof. Moncho Gomez Gesteira,  Prof. Benedict Rogers,
 Dr Georgios Fourtakas, Prof. Peter Stansby, Dr Ricardo Canelas,
 Dr Renato Vacondio, Dr Corrado Altomare, Dr Angelo Tafuni,
 Orlando Garcia-Feal, Dr Jose Gonzalez Cao

 EPHYSLAB Environmental Physics Laboratory, Universidade de Vigo
 School of Mechanical, Aerospace and Civil Engineering, University of Manchester

 DualSPHysics is free software: you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public License
 as published by the Free Software Foundation, either version 2.1 of
 the License, or (at your option) any later version.

 DualSPHysics is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with DualSPHysics. If not, see <http://www.gnu.org/licenses/>.

DualSPHysics4 [Symmetry] v4.4.053 (19-01-2020)
===============================================
LoadDsphConfig> .../bin/windows/DsphConfig.xml
[Select CUDA Device]
[CUDA Capable device(s)]
  Detected 1 CUDA Capable device(s)
  CUDA Driver Version / Runtime Version: 10.2 / 9.2
 
Device 0: "GeForce MX150"
  CUDA Capability Major....: 6.1
  Global memory............: 2048 MBytes
  CUDA Cores...............: 384 ( 3 Multiprocessors, 128 CUDA Cores/MP)
  GPU Max Clock rate.......: 1532 MHz (1.53 GHz)
  Memory Clock rate........: 3004 Mhz
  Memory Bus Width.........: 64-bit
  L2 Cache Size............: 512 KBytes
  Constant memory..........: 64 KBytes
  Shared memory per block..: 48 KBytes
  Registers per block......: 65536
  Maximum threads per MP...: 2048
  Maximum threads per block: 1024
  Concurrent copy and kernel execution....: Yes with 5 copy engine(s)
  Run time limit on kernels...............: No
  Integrated GPU sharing Host Memory......: No
  Support host page-locked memory mapping.: Yes
  Device has ECC support..................: Disabled
  CUDA Device Driver Mode (TCC or WDDM)...: WDDM (Windows Display Driver Model)
  Device supports Unified Addressing (UVA): Yes
  Device PCI (Domain / Bus / location)....: 0 / 1 / 0
  Device supports P2P and RDMA............: No
 
[GPU Hardware]
Device default: 0  "GeForce MX150"
Compute capability: 6.1
Memory global: 2048 MB
Memory shared: 49152 Bytes

[Initialising JSphGpuSingle  04-06-2020 16:06:31]
ProgramFile=".../bin/windows/DualSPHysics4.4_win64.exe"
ExecutionDir=".../FreeCAD/Mod/DesignSPHysics"
XmlFile=".../S3/S3_out/S3.xml"
OutputDir=".../S3/S3/S3_out"
OutputDataDir=".../S3/S3/S3_out"
**Basic case configuration is loaded
**Special case configuration is loaded
Loading initial state of particles...
Loaded particles: 8000
MapRealPos(border)=(-0.25,-0.0519615,-0.0519615)-(49.75,9.55196,1.55196)
MapRealPos(final)=(-0.25,-0.0519615,-0.0519615)-(49.75,9.55196,1.55196)
**Initial state of particles is loaded
**3D-Simulation parameters:
CaseName="S3"
RunName="S3"
Symmetry=False
SavePosDouble=False
SvTimers=True
Boundary="DBC"
StepAlgorithm="Symplectic"
Kernel="Wendland"
Viscosity="Artificial"
  Visco=0.020000
  ViscoBoundFactor=0.000000
DensityDiffusion="None"
Shifting="None"
RigidAlgorithm="None"
FloatingCount=0
CaseNp=8000
CaseNbound=0
CaseNfixed=0
CaseNmoving=0
CaseNfloat=0
CaseNfluid=8000
PeriodicActive="Axis-X"
PeriodicXinc=(-50,0,0)
Dx=0.5
H=1.039230
CoefficientH=1.2
CteB=514285.718750
Gamma=7.000000
RhopZero=1000.000000
Cs0=60
CFLnumber=0.200000
DtIni=0.0173205
DtMin=0.000866025
DtAllParticles=False
MassFluid=125.000000
MassBound=125.000000
Awen (Wendland)=0.372231
Bwen (Wendland)=-1.790904
TimeMax=3
TimePart=0.025
Gravity=(0.000000,0.000000,-9.810000)
NpMinimum=0
RhopOut=True
RhopOutMin=700.000000
RhopOutMax=1300.000000
WrnPartsOut=True
**Requested GPU memory for 8010 particles: 1.3 MB (0 times).
CellMode="2H"
Hdiv=1
MapCells=(27,5,1)
DomCells=(27,5,1)
DomCellCode="14_10_9"
PosCellCode="13_10_9 (8192,1024,512)"
 
BlockSize calculation mode: Fixed.
  BsForcesBound=128 (42 regs)
  BsForcesFluid=128 (52 regs)
 
**JSphGpu: Requesting gpu memory for 9082 particles: 1.5 MB.
**CellDiv: Requested gpu memory for 9082 particles: 0.1 MB.
**CellDiv: Requested gpu memory for 324 cells (CellMode=2H): 0.0 MB.
 
RunMode="Pos-Cell - Single-Gpu"
 
Particle summary:
  Fixed....: 0
  Moving...: 0
  Floating.: 0
  Fluid....: 8000  id:(0-7999)   MKs:1 (1)

Total particles: 8000 (bound=0 (fx=0 mv=0 ft=0) fluid=8000)
Total MK blocks: 1 (bound=0 (fx=0 mv=0 ft=0) fluid=1)
 
Wave paddles configuration:

*** Exception (JWavePaddleRegular::CheckConfig)
Text: Paddle without range of motion particles valid.

Finished execution (code=1

**Comment by jmdalonso** [comment]
The movement of the paddles is applied to boundary particles and in your simulation there is only fluid particles.

Best regards
