### ISSUE TITLE
Error when refference density is more than 1000 kg/m3

### ISSUE THREAD

**Issue by Salehmeiabadi** [DualSPHysics/DesignSPHysics#77]
Hi there
I increased the reference density from 1000 to 1500 or more.
After finishing the simulation and for post-processing with Para-view, the fluid particles suddenly vanish, and only the floating body remains.
1: When the fluid particles and floating particles are imported into the Para-view:
![1](https://user-images.githubusercontent.com/64735834/83874548-aac50300-a703-11ea-8ce8-6c1c151a0466.jpg)
2: When I play the simulation.
![2](https://user-images.githubusercontent.com/64735834/83875129-92091d00-a704-11ea-95dd-7e206e9b70c0.jpg)
Only floating body remains and moves.
I did everything to solve this issue:
- I increased the number of particles
- I decreased CFL number.
- I used shifting algorithm and delta SPH.
But I could not solve the problem.

**Comment by zlotny** [comment]
Hi there! 

You should change the minimum and maximum valid values for rhop on the Execution Parameters window:

![image](https://user-images.githubusercontent.com/6155245/84577341-bf686180-adbb-11ea-8588-7bd1969759c1.png)

That may be your problem

**Comment by Salehmeiabadi** [comment]
Thanks a lot.
I did not notice.
