### ISSUE TITLE
DualSphysics vs DesignSphysics

### ISSUE THREAD

**Issue by CirclestheSecond** [DualSPHysics/DesignSPHysics#8]
Hello,
When I run the same case with the same parameters in DesignSphysics the solution gets unstable. See picture below. 
![lidDesign1](https://user-images.githubusercontent.com/43582503/54450992-c66b7480-471f-11e9-8f1b-b5762805e307.PNG)

However, with DualSphysics solution stays stable throughout the simulation.

**Comment by LoreDocasar** [comment]
Hello,
In the following link you can get more information about your question:

https://dual.sphysics.org/vanilla/discussion/1546/designsphysics-is-different-form-dualsphysics
