### ISSUE TITLE
Rectilinear motion entry boxes

### ISSUE THREAD

**Issue by ebrov** [DualSPHysics/DesignSPHysics#80]
The text boxes to enter the desired X, Y, Z velocity components and the duration in the rectilinear motion (similarly for all motion types/options) are too narrow to see a single character entered. Expanding the dialog box window does not help. Hopefully this is an easy fix.

I am running the following OS:
Ubuntu 20.04 with KDE plasma 5 desktop

**Comment by zlotny** [comment]
Thanks for noticing. Indeed it has some weird sizing. I'll check it out.

**Comment by zlotny** [comment]
It should be now fixed in the latest version (commit 225cb7702fe53b807757e222e287a754a3362a43)
