### ISSUE TITLE
output pressure results with DesignSPHysics

### ISSUE THREAD

**Issue by lntoanid** [DualSPHysics/DesignSPHysics#84]
How can i set the DSPH to calculate pressure parameter with DesignSPHysics? Is there a certain command I have to enter in additional parameters?

**Comment by zlotny** [comment]
Hi there!

To calculate pressures you should use thte MeasureTool post-processing tool:

![image](https://user-images.githubusercontent.com/6155245/99367431-3a2d2f80-28ba-11eb-8f63-38a6359da079.png)

You can then define a list of points or a grid of points where to measure. If you want to know for example the pressure values on a know point, you just add it like this:

![image](https://user-images.githubusercontent.com/6155245/99367661-89736000-28ba-11eb-9386-5d8a31f99127.png)


An then press export to generate a csv file called MeasurePart.csv with the information for pressure on the points you given.

Hope that helps.

**Comment by lntoanid** [comment]
thank you very much for the immediate response, but i was hoping for a way
to visualize the pressure field in paraview like with velocity field.
Lazaros

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Στις Τρί, 17 Νοε 2020 στις 10:52 π.μ., ο/η Andrés Vieira <
notifications@github.com> έγραψε:
