### ISSUE TITLE
Issue loading DesignSPHysics

### ISSUE THREAD

**Issue by emanueler** [DualSPHysics/DesignSPHysics#85]
I have a problem loading the module. When I try to load it I get the error on line 10 (the one from html import exclude) telling that there is no package named html. I am using Ubuntu 16.04 and I have installed python 3.7. I tried to substitute line 10 with the corresponding exclude function but then I get the following error on line 15

<type 'exceptions.SyntaxError'>: ('invalid syntax', ('/home/erossi/.FreeCAD/Mod/DesignSPHysics/mod/widgets/error_report_dialog.py', 63, 35, '    def on_details_button(self): -> None:\n'))

It seems that the module does not recognize the presence of python 3.7 and is trying to use python 2.7, that is currently installed on my machine also. There is also another version of python installed, the 3.5, that is the one Ubuntu 16.04 normally uses.
Is there a way to overcome this problem?

**Comment by zlotny** [comment]
Hi there. It seems that the interpreter used to parse those lines does not support type hints / annotations yet. So probably Python 3.5 or lower.

I don't know exactly the way in which the FreeCAD Ubuntu package uses python. Usually FreeCAD includes its own Python interpreter but maybe in Ubuntu's case it's using the one in the system. If that's the case I'm afraid I can't help as much, as it's a problem with FreeCAD itself. Searching a bit in Google shows me that you can specify the python interpreter to use when you build the FreeCAD binaries. 

However I'm assuming that you're using the FreeCAD package from Ubuntu. [Here it says](https://packages.ubuntu.com/xenial/freecad) that for 16.04 the package is FreeCAD 0.15, which is from 2015 and it's not supported anymore. However if that's the case you should had a prompt appearing on screen when executing DesignSPHysics.

Can you check the version of FreeCAD that you're using and, if it's old, try to install a newer one? Maybe that solve the problem.

Sorry for the late reply, this issue somehow slipped trough my mail :(

**Comment by emanueler** [comment]
Sorry for the late reply. I managed to install freecad 0.18 downloading it from the repository frecad-maintainers/freecad-stable.

However I didn't specify the interpreter to use so maybe I should try to rebuild the binaries in the correct way.
