### ISSUE TITLE
Incompatible python version with  FreeCAD 0.18 - python 3.x

### ISSUE THREAD

**Issue by mhechthz** [DualSPHysics/DesignSPHysics#9]
FreeCAD 0.18 uses python 3.x so the plugin doesn't work any longer. Automatic conversion to python 3.x doesn't help since there are at least two more problems:

1. utf-8 hack
```
import imp
imp.reload(sys)
sys.defaultencoding('utf-8')
```
doesn't work anymore and has to be removed from all files.

2. "strange" string formatting for path
I didn't get it totally, but the json/decode.py of FreeCAD 0.18 and there the raw_decode method is not able to parse the path settings of dualsphysics since the passed string is oddly formatted. The only workaround was this one:
```
def raw_decode(self, s, idx=0):
...
s1 = s
s  = ""
for c in s1: s += str(c)
s = s.strip()
...
```
I'm sure this isn't hte most efficient way, but at least worked for me.

**Comment by cifuentesemilio2010** [comment]
@mhechthz Dear mhechthz, this the reason that the freecad 0.18 is not openning the macro? thanks

**Comment by LoreDocasar** [comment]
FreeCAD was working with python 2.x, but in this new version 0.18 they have changed to python 3.x.
Currently, the available version of the macro can't be run in FreeCAD 0.18, but we are working to make it compatible as soon as possible.

The new version of DesignSPHysics will be ready soon, at the moment, for use macro correctly it must be run in FreeCAD 0.17.

Thanks for your comments!

**Comment by cifuentesemilio2010** [comment]
Thank you very much.

Regards,
Emilio C.

**Comment by mhechthz** [comment]
@LoreDocasar Follow the instructions I posted and the plug-in should work, since it seems to work now for me. But I didn't test it in detail.

**Comment by LoreDocasar** [comment]
The new version of the macro is ready.
This new version is already compatible with FreeCAD 0.18, so it does NOT work with FreeCAD 0.17

You can download it from the official page:

https://design.sphysics.org/

Or from github:

https://github.com/DualSPHysics/DesignSPHysics

Thanks for your comments!
