### ISSUE TITLE
the issue shen use DesignSPHysics

### ISSUE THREAD

**Issue by ding-s1227** [DualSPHysics/DesignSPHysics#90]
Hi, when i use the new version to simulate the wave by FreeCAD0.19, it can't run Gencase and report as next, can you help me?
DesignSPHysics version: 0.6.0.1911-07-2

Exception type: <class 'IndexError'>

Exception value: list index out of range

Traceback:
  File "D:\FREECAD\Mod\DesignSPHysics-0.6.0.1911-07-2\mod\widgets\dock\dock_pre_processing_widget.py", line 210, in on_execute_gencase
    output = str(process.readAllStandardOutput()).replace("\\n", "\n").split("================================")[1]

**Comment by zlotny** [comment]
Hi there. Your version of DesignSPHyiscs is very outdated (07/11/2019, from the version number).

This issue was fixed in later releases. Please install a new one to get the problem fixed.
