### ISSUE TITLE
Troubles running rotational motion with sloshing tank tutorial from DSPH website

### ISSUE THREAD

**Issue by nmathias** [DualSPHysics/DesignSPHysics#93]
Hi! 
I'm new to FreeCAD and DSPH and I was trying to run the Gencase for the sloshing tank example and the code gave an error with the following notice: 

" File "C:\Users\...\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\widgets\dock\dock_simulation_widget.py", line 158, in on_fs_change
    with open(Case.the().path + "/" + Case.the().name + "_out/Run.out", "r", encoding="utf-8") as run_file:"

**Comment by zlotny** [comment]
Hi there, what version are you using?

That issue seems familiar to me and I believe it was fixed before. Can you paste the actual error message? The one in the details pane:
![imagen](https://user-images.githubusercontent.com/6155245/117659468-42489680-b19c-11eb-863b-bce33edc27f1.png)

**Comment by nmathias** [comment]
Hi! 
I'm using V5.0.3. I managed to solve te error in the meantime. It had to do with the additional parameter "-domain_fixed;...". 
The error I got from FreeCAD is:
![imagem](https://user-images.githubusercontent.com/83830989/117661770-b41de180-b196-11eb-977b-0572dd9f0cfd.png)

**Comment by zlotny** [comment]
Hi  there, that version is from even before 2019 so it is really outdated. I'm glad you solved your issue but I would advise you to install a newer version of DesignSPHyisics
