### ISSUE TITLE
How to use Boundaryvtk

### ISSUE THREAD

**Issue by Toyo-Masuda** [DualSPHysics/DesignSPHysics#94]
Hi, I am using DesignSPHysics all the time.
Thanks for the great tool.

I have a question.

In the post-processing after running the simulation, I want to output a Boundary Vtk file. It is not a particle Vtk.

However, in the Post-processing section of my DesignSPHysics, there is only [PartVTK/ComputeForce/IsoSurface/FloatingInfo/MeasureTool/FloeTool].
What do I need to do to use Boundaryvtk?

The version of DesignSPHysics is 0.6.1.2102-24-04.

**Comment by zlotny** [comment]
Hi there. BoundaryVTK is not implemented in the GUI as of right now, as we provide only the tools needed for the examples and workshops the team makes from time to time. Sorry about that. I want to emphasize that DesignSPHyiscs is not meant to be an alternative tool to command-line DualSPHyiscs, but a learning resource.

You can always just run BoundaryVTK in the command line for your specific case after the simulation is finished.
