### ISSUE TITLE
"Cannot open the file" error when initializing Inlet/Outlet 

### ISSUE THREAD

**Issue by GaoyuanWu** [DualSPHysics/DesignSPHysics#95]
**Version**: DualSPHysics5 v5.0.175 (21-02-2021), DesignSPHysics 0.6.1.2102-24-04, and FreeCAD 0.19
**Issue**: Imposing inlet buffer particles' velocity that varies in time using `waves.csv` , which is a file from  `examples\inletoutlet\04_Waves2D` in DualSPHysics (although my model is different from the example). 
When I run with DesignSPHysics I get the error: 
```
Initialising InOut...

*** Exception (JReadDatafile::LoadFile) at ..\source\JReadDatafile.cpp:77
Text: Cannot open the file.
File: Mypath/waves.csv
```
I've tried running `examples\inletoutlet\04_Waves2D` with DualSPHysics using command line and it didn't give such error when loading the file `waves.csv` .
I am not sure if it's due to **my modeling setup**, or **Plugin Setup**, or **DesignSPHysics**.

Thanks for your help in advance.

**Comment by GaoyuanWu** [comment]
I think I figured it out  where the error came from.
When the user browses the velocity file in **Inlet/Outlet object edit** window, the **file path** generated in `Case.xml` is the **absolute path** instead of the **relative path**.
That's how it went wrong. And we can simply type in the relative path in the box instead of browsing to resolve this issue.
Thanks!

**Comment by zlotny** [comment]
Thank you for noticing that, I'll try to replicate the issue to see what happens with absolute paths. DualSPHysics should be able to find your waves.csv file with an absolute path I think. I'll check it out when I can.
