### ISSUE TITLE
Where can I find the file that records the position of each particle at each moment?

### ISSUE THREAD

**Issue by zhu-hui-ling** [DualSPHysics/DesignSPHysics#96]

**Comment by zlotny** [comment]
Hi there. You can see and analyze the position and properties of each particle in each point of time exporting the simulation data with PartVTK
![image](https://user-images.githubusercontent.com/6155245/149931838-92472c69-744f-4327-afb9-ae627d9f0667.png)


You can  then open those files, PartAll[...].vtk in this case, with a software like Paraview to see whatever you want in the particle, including the position at each point in time.
