### ISSUE TITLE
Can I set the particle density at different positions in the same simulation?

### ISSUE THREAD

**Issue by zhu-hui-ling** [DualSPHysics/DesignSPHysics#97]
Can I set the particle density at different positions in the same simulation?
If possible, how to set it?

**Comment by zlotny** [comment]
If you're referring to setting the distance between particles to different values depending on where particles are on the case it is not possible with DesignSPHyiscs.

I don't know if that is possible in DualSPHyiscs, the command line tool. I know there was some demos and tests around this feature but as far as I know it is not implemented yet.

You can ask about that on the DualSPHyiscs forums (forums.dual.sphysics.org) or in the DualSPhysics repo (https://github.com/DualSPHysics/DualSPHysics)
