### ISSUE TITLE
Assigning materials issue

### ISSUE THREAD

**Issue by ClementB81** [DualSPHysics/DesignSPHysics#99]
Hello,

I have an issue assigning material's properties to floating bodies in my simulation. My case is composed of several floating bodies of the same material and I am using the Project Chrono coupling to solve contacts. I can assign the material for the first body but for the second one the error "Name Value already exist" appears when running the GenCase. I tried to change the material of the second body and it works so I think the error appears when different bodies are linked to the same material. Is this a DesignSPhysics issue or is there something I can do for my case to solve that ?

Thank you

Clement

**Comment by zlotny** [comment]
This seems to be the same issue than #101 but I now see why the error is present, as materials.xml contains the same property twice and GenCase throws an error.

It should be fixed on fe118fe1f9c38c621fd65ba2e7dcf622e169bf47

Thanks for reporting it!
